/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicApp } from './public-app';

/**
 * 
 * @export
 * @interface AppBotRelationshipsApp
 */
export interface AppBotRelationshipsApp {
    /**
     * 
     * @type {PublicApp}
     * @memberof AppBotRelationshipsApp
     */
    'data'?: PublicApp;
}

