/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppInstallWithClientAttributes
 */
export interface AppInstallWithClientAttributes {
    /**
     * 
     * @type {string}
     * @memberof AppInstallWithClientAttributes
     */
    'client_id': string;
    /**
     * 
     * @type {string}
     * @memberof AppInstallWithClientAttributes
     */
    'client_secret': string;
}

