/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppPatchRequestDataAttributes } from './app-patch-request-data-attributes';

/**
 * 
 * @export
 * @interface AppPatchRequestData
 */
export interface AppPatchRequestData {
    /**
     * 
     * @type {AppPatchRequestDataAttributes}
     * @memberof AppPatchRequestData
     */
    'attributes'?: AppPatchRequestDataAttributes;
    /**
     * 
     * @type {string}
     * @memberof AppPatchRequestData
     */
    'type'?: AppPatchRequestDataTypeEnum;
}

type AppPatchRequestDataTypeEnum = 'app'


