/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppInstallDataRelationshipsApp } from './app-install-data-relationships-app';

/**
 * 
 * @export
 * @interface AppInstallDataRelationships
 */
export interface AppInstallDataRelationships {
    /**
     * 
     * @type {AppInstallDataRelationshipsApp}
     * @memberof AppInstallDataRelationships
     */
    'app'?: AppInstallDataRelationshipsApp;
}

