/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppInstallDataAttributes } from './app-install-data-attributes';
import { AppInstallDataRelationships } from './app-install-data-relationships';
import { Links } from './links';

/**
 * 
 * @export
 * @interface AppInstallData
 */
export interface AppInstallData {
    /**
     * 
     * @type {AppInstallDataAttributes}
     * @memberof AppInstallData
     */
    'attributes': AppInstallDataAttributes;
    /**
     * 
     * @type {string}
     * @memberof AppInstallData
     */
    'id': string;
    /**
     * 
     * @type {Links}
     * @memberof AppInstallData
     */
    'links'?: Links;
    /**
     * 
     * @type {AppInstallDataRelationships}
     * @memberof AppInstallData
     */
    'relationships'?: AppInstallDataRelationships;
    /**
     * 
     * @type {string}
     * @memberof AppInstallData
     */
    'type': string;
}

