/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppResourceAttributesWithSecret } from './app-resource-attributes-with-secret';

/**
 * 
 * @export
 * @interface AppDataWithSecret
 */
export interface AppDataWithSecret {
    /**
     * 
     * @type {AppResourceAttributesWithSecret}
     * @memberof AppDataWithSecret
     */
    'attributes': AppResourceAttributesWithSecret;
    /**
     * 
     * @type {string}
     * @memberof AppDataWithSecret
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AppDataWithSecret
     */
    'type': string;
}

