/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppDataWithSecret } from './app-data-with-secret';
import { JsonApi } from './json-api';
import { SelfLink } from './self-link';

/**
 * 
 * @export
 * @interface AppPostResponse
 */
export interface AppPostResponse {
    /**
     * 
     * @type {AppDataWithSecret}
     * @memberof AppPostResponse
     */
    'data'?: AppDataWithSecret;
    /**
     * 
     * @type {JsonApi}
     * @memberof AppPostResponse
     */
    'jsonapi'?: JsonApi;
    /**
     * 
     * @type {SelfLink}
     * @memberof AppPostResponse
     */
    'links'?: SelfLink;
}

