/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppResourceAttributesWithSecret } from './app-resource-attributes-with-secret';

/**
 * 
 * @export
 * @interface AppDataWithSecret
 */
export interface AppDataWithSecret {
    /**
     * 
     * @type {AppResourceAttributesWithSecret}
     * @memberof AppDataWithSecret
     */
    'attributes': AppResourceAttributesWithSecret;
    /**
     * 
     * @type {string}
     * @memberof AppDataWithSecret
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AppDataWithSecret
     */
    'type': string;
}

