/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppBotRelationships } from './app-bot-relationships';
import { Links } from './links';

/**
 * 
 * @export
 * @interface AppBot
 */
export interface AppBot {
    /**
     * 
     * @type {object}
     * @memberof AppBot
     */
    'attributes'?: object;
    /**
     * 
     * @type {string}
     * @memberof AppBot
     */
    'id': string;
    /**
     * 
     * @type {Links}
     * @memberof AppBot
     */
    'links'?: Links;
    /**
     * 
     * @type {AppBotRelationships}
     * @memberof AppBot
     */
    'relationships': AppBotRelationships;
    /**
     * 
     * @type {string}
     * @memberof AppBot
     */
    'type': string;
}

