/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsCreateOrganizationAppResponseErrorsInner } from './apps-create-organization-app-response-errors-inner';
import { AppsCreateOrganizationAppResponseJsonapi } from './apps-create-organization-app-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsCreateOrganizationAppResponse
 */
export interface AppsCreateOrganizationAppResponse {
    /**
     * 
     * @type {Array<AppsCreateOrganizationAppResponseErrorsInner>}
     * @memberof AppsCreateOrganizationAppResponse
     */
    'errors': Array<AppsCreateOrganizationAppResponseErrorsInner>;
    /**
     * 
     * @type {AppsCreateOrganizationAppResponseJsonapi}
     * @memberof AppsCreateOrganizationAppResponse
     */
    'jsonapi': AppsCreateOrganizationAppResponseJsonapi;
}

