/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsRevokeGroupAppInstall409ResponseErrorsInner } from './apps-revoke-group-app-install409-response-errors-inner';
import { AppsRevokeGroupAppInstall409ResponseJsonapi } from './apps-revoke-group-app-install409-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsRevokeGroupAppInstall409Response
 */
export interface AppsRevokeGroupAppInstall409Response {
    /**
     * 
     * @type {Array<AppsRevokeGroupAppInstall409ResponseErrorsInner>}
     * @memberof AppsRevokeGroupAppInstall409Response
     */
    'errors': Array<AppsRevokeGroupAppInstall409ResponseErrorsInner>;
    /**
     * 
     * @type {AppsRevokeGroupAppInstall409ResponseJsonapi}
     * @memberof AppsRevokeGroupAppInstall409Response
     */
    'jsonapi': AppsRevokeGroupAppInstall409ResponseJsonapi;
}

