/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsRevokeBotAuthorization404ResponseErrorsInner } from './apps-revoke-bot-authorization404-response-errors-inner';
import { AppsRevokeBotAuthorization404ResponseJsonapi } from './apps-revoke-bot-authorization404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsRevokeBotAuthorization404Response
 */
export interface AppsRevokeBotAuthorization404Response {
    /**
     * 
     * @type {Array<AppsRevokeBotAuthorization404ResponseErrorsInner>}
     * @memberof AppsRevokeBotAuthorization404Response
     */
    'errors': Array<AppsRevokeBotAuthorization404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsRevokeBotAuthorization404ResponseJsonapi}
     * @memberof AppsRevokeBotAuthorization404Response
     */
    'jsonapi': AppsRevokeBotAuthorization404ResponseJsonapi;
}

