/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppInstallData } from './app-install-data';
import { JsonApi } from './json-api';
import { PaginatedLinks } from './paginated-links';

/**
 * 
 * @export
 * @interface AppsListOrgInstallsResponse
 */
export interface AppsListOrgInstallsResponse {
    /**
     * 
     * @type {Array<AppInstallData>}
     * @memberof AppsListOrgInstallsResponse
     */
    'data': Array<AppInstallData>;
    /**
     * 
     * @type {JsonApi}
     * @memberof AppsListOrgInstallsResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {PaginatedLinks}
     * @memberof AppsListOrgInstallsResponse
     */
    'links': PaginatedLinks;
}

