/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListApps403ResponseErrorsInner } from './apps-list-apps403-response-errors-inner';
import { AppsListApps403ResponseJsonapi } from './apps-list-apps403-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListApps403Response
 */
export interface AppsListApps403Response {
    /**
     * 
     * @type {Array<AppsListApps403ResponseErrorsInner>}
     * @memberof AppsListApps403Response
     */
    'errors': Array<AppsListApps403ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListApps403ResponseJsonapi}
     * @memberof AppsListApps403Response
     */
    'jsonapi': AppsListApps403ResponseJsonapi;
}

