/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsCreateNewAppForOrganization500ResponseErrorsInner } from './apps-create-new-app-for-organization500-response-errors-inner';
import { AppsCreateNewAppForOrganization500ResponseJsonapi } from './apps-create-new-app-for-organization500-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsCreateNewAppForOrganization500Response
 */
export interface AppsCreateNewAppForOrganization500Response {
    /**
     * 
     * @type {Array<AppsCreateNewAppForOrganization500ResponseErrorsInner>}
     * @memberof AppsCreateNewAppForOrganization500Response
     */
    'errors': Array<AppsCreateNewAppForOrganization500ResponseErrorsInner>;
    /**
     * 
     * @type {AppsCreateNewAppForOrganization500ResponseJsonapi}
     * @memberof AppsCreateNewAppForOrganization500Response
     */
    'jsonapi': AppsCreateNewAppForOrganization500ResponseJsonapi;
}

