/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsManageClientSecretForSnykApp409ResponseErrorsInner } from './apps-manage-client-secret-for-snyk-app409-response-errors-inner';
import { AppsManageClientSecretForSnykApp409ResponseJsonapi } from './apps-manage-client-secret-for-snyk-app409-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsManageClientSecretForSnykApp409Response
 */
export interface AppsManageClientSecretForSnykApp409Response {
    /**
     * 
     * @type {Array<AppsManageClientSecretForSnykApp409ResponseErrorsInner>}
     * @memberof AppsManageClientSecretForSnykApp409Response
     */
    'errors': Array<AppsManageClientSecretForSnykApp409ResponseErrorsInner>;
    /**
     * 
     * @type {AppsManageClientSecretForSnykApp409ResponseJsonapi}
     * @memberof AppsManageClientSecretForSnykApp409Response
     */
    'jsonapi': AppsManageClientSecretForSnykApp409ResponseJsonapi;
}

