/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsUpdateCreationAttributesById409ResponseErrorsInner } from './apps-update-creation-attributes-by-id409-response-errors-inner';
import { AppsUpdateCreationAttributesById409ResponseJsonapi } from './apps-update-creation-attributes-by-id409-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsUpdateCreationAttributesById409Response
 */
export interface AppsUpdateCreationAttributesById409Response {
    /**
     * 
     * @type {Array<AppsUpdateCreationAttributesById409ResponseErrorsInner>}
     * @memberof AppsUpdateCreationAttributesById409Response
     */
    'errors': Array<AppsUpdateCreationAttributesById409ResponseErrorsInner>;
    /**
     * 
     * @type {AppsUpdateCreationAttributesById409ResponseJsonapi}
     * @memberof AppsUpdateCreationAttributesById409Response
     */
    'jsonapi': AppsUpdateCreationAttributesById409ResponseJsonapi;
}

