/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListGroupAppInstalls400ResponseErrorsInner } from './apps-list-group-app-installs400-response-errors-inner';
import { AppsListGroupAppInstalls400ResponseJsonapi } from './apps-list-group-app-installs400-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListGroupAppInstalls400Response
 */
export interface AppsListGroupAppInstalls400Response {
    /**
     * 
     * @type {Array<AppsListGroupAppInstalls400ResponseErrorsInner>}
     * @memberof AppsListGroupAppInstalls400Response
     */
    'errors': Array<AppsListGroupAppInstalls400ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListGroupAppInstalls400ResponseJsonapi}
     * @memberof AppsListGroupAppInstalls400Response
     */
    'jsonapi': AppsListGroupAppInstalls400ResponseJsonapi;
}

