/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListApps401ResponseErrorsInner } from './apps-list-apps401-response-errors-inner';
import { AppsListApps401ResponseJsonapi } from './apps-list-apps401-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListApps401Response
 */
export interface AppsListApps401Response {
    /**
     * 
     * @type {Array<AppsListApps401ResponseErrorsInner>}
     * @memberof AppsListApps401Response
     */
    'errors': Array<AppsListApps401ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListApps401ResponseJsonapi}
     * @memberof AppsListApps401Response
     */
    'jsonapi': AppsListApps401ResponseJsonapi;
}

