/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsByInstallIdResponseErrorsInner } from './apps-by-install-id-response-errors-inner';
import { AppsByInstallIdResponseJsonapi } from './apps-by-install-id-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsByInstallIdResponse
 */
export interface AppsByInstallIdResponse {
    /**
     * 
     * @type {Array<AppsByInstallIdResponseErrorsInner>}
     * @memberof AppsByInstallIdResponse
     */
    'errors': Array<AppsByInstallIdResponseErrorsInner>;
    /**
     * 
     * @type {AppsByInstallIdResponseJsonapi}
     * @memberof AppsByInstallIdResponse
     */
    'jsonapi': AppsByInstallIdResponseJsonapi;
}

