/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsInstallSnykAppToOrgRequestRelationshipsAppData } from './apps-install-snyk-app-to-org-request-relationships-app-data';

/**
 * 
 * @export
 * @interface AppsInstallSnykAppToOrgRequestRelationshipsApp
 */
export interface AppsInstallSnykAppToOrgRequestRelationshipsApp {
    /**
     * 
     * @type {AppsInstallSnykAppToOrgRequestRelationshipsAppData}
     * @memberof AppsInstallSnykAppToOrgRequestRelationshipsApp
     */
    'data': AppsInstallSnykAppToOrgRequestRelationshipsAppData;
}

