/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListOrgInstalls500ResponseErrorsInner } from './apps-list-org-installs500-response-errors-inner';
import { AppsListOrgInstalls500ResponseJsonapi } from './apps-list-org-installs500-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListOrgInstalls500Response
 */
export interface AppsListOrgInstalls500Response {
    /**
     * 
     * @type {Array<AppsListOrgInstalls500ResponseErrorsInner>}
     * @memberof AppsListOrgInstalls500Response
     */
    'errors': Array<AppsListOrgInstalls500ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListOrgInstalls500ResponseJsonapi}
     * @memberof AppsListOrgInstalls500Response
     */
    'jsonapi': AppsListOrgInstalls500ResponseJsonapi;
}

