/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsCreateOrganizationApp401ResponseErrorsInner } from './apps-create-organization-app401-response-errors-inner';
import { AppsCreateOrganizationApp401ResponseJsonapi } from './apps-create-organization-app401-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsCreateOrganizationApp401Response
 */
export interface AppsCreateOrganizationApp401Response {
    /**
     * 
     * @type {Array<AppsCreateOrganizationApp401ResponseErrorsInner>}
     * @memberof AppsCreateOrganizationApp401Response
     */
    'errors': Array<AppsCreateOrganizationApp401ResponseErrorsInner>;
    /**
     * 
     * @type {AppsCreateOrganizationApp401ResponseJsonapi}
     * @memberof AppsCreateOrganizationApp401Response
     */
    'jsonapi': AppsCreateOrganizationApp401ResponseJsonapi;
}

