/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsInstallGroupApp500ResponseErrorsInner } from './apps-install-group-app500-response-errors-inner';
import { AppsInstallGroupApp500ResponseJsonapi } from './apps-install-group-app500-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsInstallGroupApp500Response
 */
export interface AppsInstallGroupApp500Response {
    /**
     * 
     * @type {Array<AppsInstallGroupApp500ResponseErrorsInner>}
     * @memberof AppsInstallGroupApp500Response
     */
    'errors': Array<AppsInstallGroupApp500ResponseErrorsInner>;
    /**
     * 
     * @type {AppsInstallGroupApp500ResponseJsonapi}
     * @memberof AppsInstallGroupApp500Response
     */
    'jsonapi': AppsInstallGroupApp500ResponseJsonapi;
}

