/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListOrgInstalls401ResponseErrorsInner } from './apps-list-org-installs401-response-errors-inner';
import { AppsListOrgInstalls401ResponseJsonapi } from './apps-list-org-installs401-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListOrgInstalls401Response
 */
export interface AppsListOrgInstalls401Response {
    /**
     * 
     * @type {Array<AppsListOrgInstalls401ResponseErrorsInner>}
     * @memberof AppsListOrgInstalls401Response
     */
    'errors': Array<AppsListOrgInstalls401ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListOrgInstalls401ResponseJsonapi}
     * @memberof AppsListOrgInstalls401Response
     */
    'jsonapi': AppsListOrgInstalls401ResponseJsonapi;
}

