/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsInstallGroupAppRequestRelationshipsAppData } from './apps-install-group-app-request-relationships-app-data';

/**
 * 
 * @export
 * @interface AppsInstallGroupAppRequestRelationshipsApp
 */
export interface AppsInstallGroupAppRequestRelationshipsApp {
    /**
     * 
     * @type {AppsInstallGroupAppRequestRelationshipsAppData}
     * @memberof AppsInstallGroupAppRequestRelationshipsApp
     */
    'data': AppsInstallGroupAppRequestRelationshipsAppData;
}

