/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsRevokeByInstallId404ResponseErrorsInner } from './apps-revoke-by-install-id404-response-errors-inner';
import { AppsRevokeByInstallId404ResponseJsonapi } from './apps-revoke-by-install-id404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsRevokeByInstallId404Response
 */
export interface AppsRevokeByInstallId404Response {
    /**
     * 
     * @type {Array<AppsRevokeByInstallId404ResponseErrorsInner>}
     * @memberof AppsRevokeByInstallId404Response
     */
    'errors': Array<AppsRevokeByInstallId404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsRevokeByInstallId404ResponseJsonapi}
     * @memberof AppsRevokeByInstallId404Response
     */
    'jsonapi': AppsRevokeByInstallId404ResponseJsonapi;
}

