/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsInstallSnykAppToOrgRequestData } from './apps-install-snyk-app-to-org-request-data';
import { AppsInstallSnykAppToOrgRequestRelationships } from './apps-install-snyk-app-to-org-request-relationships';

/**
 * 
 * @export
 * @interface AppsInstallSnykAppToOrgRequest
 */
export interface AppsInstallSnykAppToOrgRequest {
    /**
     * 
     * @type {AppsInstallSnykAppToOrgRequestData}
     * @memberof AppsInstallSnykAppToOrgRequest
     */
    'data': AppsInstallSnykAppToOrgRequestData;
    /**
     * 
     * @type {AppsInstallSnykAppToOrgRequestRelationships}
     * @memberof AppsInstallSnykAppToOrgRequest
     */
    'relationships': AppsInstallSnykAppToOrgRequestRelationships;
}

