/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsGetByClientId404ResponseErrorsInner } from './apps-get-by-client-id404-response-errors-inner';
import { AppsGetByClientId404ResponseJsonapi } from './apps-get-by-client-id404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsGetByClientId404Response
 */
export interface AppsGetByClientId404Response {
    /**
     * 
     * @type {Array<AppsGetByClientId404ResponseErrorsInner>}
     * @memberof AppsGetByClientId404Response
     */
    'errors': Array<AppsGetByClientId404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsGetByClientId404ResponseJsonapi}
     * @memberof AppsGetByClientId404Response
     */
    'jsonapi': AppsGetByClientId404ResponseJsonapi;
}

