/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppData } from './app-data';
import { JsonApi } from './json-api';
import { SelfLink } from './self-link';

/**
 * 
 * @export
 * @interface AppsGetByAppIdResponse
 */
export interface AppsGetByAppIdResponse {
    /**
     * 
     * @type {AppData}
     * @memberof AppsGetByAppIdResponse
     */
    'data'?: AppData;
    /**
     * 
     * @type {JsonApi}
     * @memberof AppsGetByAppIdResponse
     */
    'jsonapi'?: JsonApi;
    /**
     * 
     * @type {SelfLink}
     * @memberof AppsGetByAppIdResponse
     */
    'links'?: SelfLink;
}

