/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsRevokeAppByIdResponseErrorsInner } from './apps-revoke-app-by-id-response-errors-inner';
import { AppsRevokeAppByIdResponseJsonapi } from './apps-revoke-app-by-id-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsRevokeAppByIdResponse
 */
export interface AppsRevokeAppByIdResponse {
    /**
     * 
     * @type {Array<AppsRevokeAppByIdResponseErrorsInner>}
     * @memberof AppsRevokeAppByIdResponse
     */
    'errors': Array<AppsRevokeAppByIdResponseErrorsInner>;
    /**
     * 
     * @type {AppsRevokeAppByIdResponseJsonapi}
     * @memberof AppsRevokeAppByIdResponse
     */
    'jsonapi': AppsRevokeAppByIdResponseJsonapi;
}

