/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsUpdateAttributes404ResponseErrorsInner } from './apps-update-attributes404-response-errors-inner';
import { AppsUpdateAttributes404ResponseJsonapi } from './apps-update-attributes404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsUpdateAttributes404Response
 */
export interface AppsUpdateAttributes404Response {
    /**
     * 
     * @type {Array<AppsUpdateAttributes404ResponseErrorsInner>}
     * @memberof AppsUpdateAttributes404Response
     */
    'errors': Array<AppsUpdateAttributes404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsUpdateAttributes404ResponseJsonapi}
     * @memberof AppsUpdateAttributes404Response
     */
    'jsonapi': AppsUpdateAttributes404ResponseJsonapi;
}

