/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsCreateNewAppForOrganization409ResponseErrorsInner } from './apps-create-new-app-for-organization409-response-errors-inner';
import { AppsCreateNewAppForOrganization409ResponseJsonapi } from './apps-create-new-app-for-organization409-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsCreateNewAppForOrganization409Response
 */
export interface AppsCreateNewAppForOrganization409Response {
    /**
     * 
     * @type {Array<AppsCreateNewAppForOrganization409ResponseErrorsInner>}
     * @memberof AppsCreateNewAppForOrganization409Response
     */
    'errors': Array<AppsCreateNewAppForOrganization409ResponseErrorsInner>;
    /**
     * 
     * @type {AppsCreateNewAppForOrganization409ResponseJsonapi}
     * @memberof AppsCreateNewAppForOrganization409Response
     */
    'jsonapi': AppsCreateNewAppForOrganization409ResponseJsonapi;
}

