/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsInstallSnykAppToOrgRequestRelationshipsApp } from './apps-install-snyk-app-to-org-request-relationships-app';

/**
 * 
 * @export
 * @interface AppsInstallSnykAppToOrgRequestRelationships
 */
export interface AppsInstallSnykAppToOrgRequestRelationships {
    /**
     * 
     * @type {AppsInstallSnykAppToOrgRequestRelationshipsApp}
     * @memberof AppsInstallSnykAppToOrgRequestRelationships
     */
    'app': AppsInstallSnykAppToOrgRequestRelationshipsApp;
}

