/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsRevokeByInstallId409ResponseErrorsInner } from './apps-revoke-by-install-id409-response-errors-inner';
import { AppsRevokeByInstallId409ResponseJsonapi } from './apps-revoke-by-install-id409-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsRevokeByInstallId409Response
 */
export interface AppsRevokeByInstallId409Response {
    /**
     * 
     * @type {Array<AppsRevokeByInstallId409ResponseErrorsInner>}
     * @memberof AppsRevokeByInstallId409Response
     */
    'errors': Array<AppsRevokeByInstallId409ResponseErrorsInner>;
    /**
     * 
     * @type {AppsRevokeByInstallId409ResponseJsonapi}
     * @memberof AppsRevokeByInstallId409Response
     */
    'jsonapi': AppsRevokeByInstallId409ResponseJsonapi;
}

