/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsUpdateCreationAttributesById403ResponseErrorsInner } from './apps-update-creation-attributes-by-id403-response-errors-inner';
import { AppsUpdateCreationAttributesById403ResponseJsonapi } from './apps-update-creation-attributes-by-id403-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsUpdateCreationAttributesById403Response
 */
export interface AppsUpdateCreationAttributesById403Response {
    /**
     * 
     * @type {Array<AppsUpdateCreationAttributesById403ResponseErrorsInner>}
     * @memberof AppsUpdateCreationAttributesById403Response
     */
    'errors': Array<AppsUpdateCreationAttributesById403ResponseErrorsInner>;
    /**
     * 
     * @type {AppsUpdateCreationAttributesById403ResponseJsonapi}
     * @memberof AppsUpdateCreationAttributesById403Response
     */
    'jsonapi': AppsUpdateCreationAttributesById403ResponseJsonapi;
}

