/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsGetByClientId400ResponseErrorsInner } from './apps-get-by-client-id400-response-errors-inner';
import { AppsGetByClientId400ResponseJsonapi } from './apps-get-by-client-id400-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsGetByClientId400Response
 */
export interface AppsGetByClientId400Response {
    /**
     * 
     * @type {Array<AppsGetByClientId400ResponseErrorsInner>}
     * @memberof AppsGetByClientId400Response
     */
    'errors': Array<AppsGetByClientId400ResponseErrorsInner>;
    /**
     * 
     * @type {AppsGetByClientId400ResponseJsonapi}
     * @memberof AppsGetByClientId400Response
     */
    'jsonapi': AppsGetByClientId400ResponseJsonapi;
}

