/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsDeleteAppById404ResponseErrorsInner } from './apps-delete-app-by-id404-response-errors-inner';
import { AppsDeleteAppById404ResponseJsonapi } from './apps-delete-app-by-id404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsDeleteAppById404Response
 */
export interface AppsDeleteAppById404Response {
    /**
     * 
     * @type {Array<AppsDeleteAppById404ResponseErrorsInner>}
     * @memberof AppsDeleteAppById404Response
     */
    'errors': Array<AppsDeleteAppById404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsDeleteAppById404ResponseJsonapi}
     * @memberof AppsDeleteAppById404Response
     */
    'jsonapi': AppsDeleteAppById404ResponseJsonapi;
}

