/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsCreateInstallSecretRequestDataAttributes } from './apps-create-install-secret-request-data-attributes';

/**
 * 
 * @export
 * @interface AppsCreateInstallSecretRequestData
 */
export interface AppsCreateInstallSecretRequestData {
    /**
     * 
     * @type {AppsCreateInstallSecretRequestDataAttributes}
     * @memberof AppsCreateInstallSecretRequestData
     */
    'attributes': AppsCreateInstallSecretRequestDataAttributes;
    /**
     * 
     * @type {string}
     * @memberof AppsCreateInstallSecretRequestData
     */
    'type': AppsCreateInstallSecretRequestDataTypeEnum;
}

type AppsCreateInstallSecretRequestDataTypeEnum = 'app'


