/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsUpdateAttributes409ResponseErrorsInner } from './apps-update-attributes409-response-errors-inner';
import { AppsUpdateAttributes409ResponseJsonapi } from './apps-update-attributes409-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsUpdateAttributes409Response
 */
export interface AppsUpdateAttributes409Response {
    /**
     * 
     * @type {Array<AppsUpdateAttributes409ResponseErrorsInner>}
     * @memberof AppsUpdateAttributes409Response
     */
    'errors': Array<AppsUpdateAttributes409ResponseErrorsInner>;
    /**
     * 
     * @type {AppsUpdateAttributes409ResponseJsonapi}
     * @memberof AppsUpdateAttributes409Response
     */
    'jsonapi': AppsUpdateAttributes409ResponseJsonapi;
}

