/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppsInstallGroupAppRequestRelationshipsAppData
 */
export interface AppsInstallGroupAppRequestRelationshipsAppData {
    /**
     * 
     * @type {string}
     * @memberof AppsInstallGroupAppRequestRelationshipsAppData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AppsInstallGroupAppRequestRelationshipsAppData
     */
    'type': AppsInstallGroupAppRequestRelationshipsAppDataTypeEnum;
}

type AppsInstallGroupAppRequestRelationshipsAppDataTypeEnum = 'app'


