/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListUserInstalledApps404ResponseErrorsInner } from './apps-list-user-installed-apps404-response-errors-inner';
import { AppsListUserInstalledApps404ResponseJsonapi } from './apps-list-user-installed-apps404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListUserInstalledApps404Response
 */
export interface AppsListUserInstalledApps404Response {
    /**
     * 
     * @type {Array<AppsListUserInstalledApps404ResponseErrorsInner>}
     * @memberof AppsListUserInstalledApps404Response
     */
    'errors': Array<AppsListUserInstalledApps404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListUserInstalledApps404ResponseJsonapi}
     * @memberof AppsListUserInstalledApps404Response
     */
    'jsonapi': AppsListUserInstalledApps404ResponseJsonapi;
}

