/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsInstallGroupAppRequestRelationshipsApp } from './apps-install-group-app-request-relationships-app';

/**
 * 
 * @export
 * @interface AppsInstallGroupAppRequestRelationships
 */
export interface AppsInstallGroupAppRequestRelationships {
    /**
     * 
     * @type {AppsInstallGroupAppRequestRelationshipsApp}
     * @memberof AppsInstallGroupAppRequestRelationships
     */
    'app': AppsInstallGroupAppRequestRelationshipsApp;
}

