/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsInstallGroupAppRequestData } from './apps-install-group-app-request-data';
import { AppsInstallGroupAppRequestRelationships } from './apps-install-group-app-request-relationships';

/**
 * 
 * @export
 * @interface AppsInstallGroupAppRequest
 */
export interface AppsInstallGroupAppRequest {
    /**
     * 
     * @type {AppsInstallGroupAppRequestData}
     * @memberof AppsInstallGroupAppRequest
     */
    'data': AppsInstallGroupAppRequestData;
    /**
     * 
     * @type {AppsInstallGroupAppRequestRelationships}
     * @memberof AppsInstallGroupAppRequest
     */
    'relationships': AppsInstallGroupAppRequestRelationships;
}

