/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsGetByClientId409ResponseErrorsInner } from './apps-get-by-client-id409-response-errors-inner';
import { AppsGetByClientId409ResponseJsonapi } from './apps-get-by-client-id409-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsGetByClientId409Response
 */
export interface AppsGetByClientId409Response {
    /**
     * 
     * @type {Array<AppsGetByClientId409ResponseErrorsInner>}
     * @memberof AppsGetByClientId409Response
     */
    'errors': Array<AppsGetByClientId409ResponseErrorsInner>;
    /**
     * 
     * @type {AppsGetByClientId409ResponseJsonapi}
     * @memberof AppsGetByClientId409Response
     */
    'jsonapi': AppsGetByClientId409ResponseJsonapi;
}

