/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListGroupAppInstalls404ResponseErrorsInner } from './apps-list-group-app-installs404-response-errors-inner';
import { AppsListGroupAppInstalls404ResponseJsonapi } from './apps-list-group-app-installs404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListGroupAppInstalls404Response
 */
export interface AppsListGroupAppInstalls404Response {
    /**
     * 
     * @type {Array<AppsListGroupAppInstalls404ResponseErrorsInner>}
     * @memberof AppsListGroupAppInstalls404Response
     */
    'errors': Array<AppsListGroupAppInstalls404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListGroupAppInstalls404ResponseJsonapi}
     * @memberof AppsListGroupAppInstalls404Response
     */
    'jsonapi': AppsListGroupAppInstalls404ResponseJsonapi;
}

