/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsCreateInstallSecretRequestData } from './apps-create-install-secret-request-data';

/**
 * 
 * @export
 * @interface AppsManageClientSecretForSnykAppRequest1
 */
export interface AppsManageClientSecretForSnykAppRequest1 {
    /**
     * 
     * @type {AppsCreateInstallSecretRequestData}
     * @memberof AppsManageClientSecretForSnykAppRequest1
     */
    'data': AppsCreateInstallSecretRequestData;
}

