/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppsRevokeAppByIdResponseJsonapi
 */
export interface AppsRevokeAppByIdResponseJsonapi {
    /**
     * Version of the JSON API specification this server supports.
     * @type {string}
     * @memberof AppsRevokeAppByIdResponseJsonapi
     */
    'version': string;
}

