/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListOrgInstalls403ResponseErrorsInner } from './apps-list-org-installs403-response-errors-inner';
import { AppsListOrgInstalls403ResponseJsonapi } from './apps-list-org-installs403-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListOrgInstalls403Response
 */
export interface AppsListOrgInstalls403Response {
    /**
     * 
     * @type {Array<AppsListOrgInstalls403ResponseErrorsInner>}
     * @memberof AppsListOrgInstalls403Response
     */
    'errors': Array<AppsListOrgInstalls403ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListOrgInstalls403ResponseJsonapi}
     * @memberof AppsListOrgInstalls403Response
     */
    'jsonapi': AppsListOrgInstalls403ResponseJsonapi;
}

