/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsRevokeGroupAppInstallResponseErrorsInner } from './apps-revoke-group-app-install-response-errors-inner';
import { AppsRevokeGroupAppInstallResponseJsonapi } from './apps-revoke-group-app-install-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsRevokeGroupAppInstallResponse
 */
export interface AppsRevokeGroupAppInstallResponse {
    /**
     * 
     * @type {Array<AppsRevokeGroupAppInstallResponseErrorsInner>}
     * @memberof AppsRevokeGroupAppInstallResponse
     */
    'errors': Array<AppsRevokeGroupAppInstallResponseErrorsInner>;
    /**
     * 
     * @type {AppsRevokeGroupAppInstallResponseJsonapi}
     * @memberof AppsRevokeGroupAppInstallResponse
     */
    'jsonapi': AppsRevokeGroupAppInstallResponseJsonapi;
}

