/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListOrgInstalls409ResponseErrorsInner } from './apps-list-org-installs409-response-errors-inner';
import { AppsListOrgInstalls409ResponseJsonapi } from './apps-list-org-installs409-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListOrgInstalls409Response
 */
export interface AppsListOrgInstalls409Response {
    /**
     * 
     * @type {Array<AppsListOrgInstalls409ResponseErrorsInner>}
     * @memberof AppsListOrgInstalls409Response
     */
    'errors': Array<AppsListOrgInstalls409ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListOrgInstalls409ResponseJsonapi}
     * @memberof AppsListOrgInstalls409Response
     */
    'jsonapi': AppsListOrgInstalls409ResponseJsonapi;
}

