/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListOrgCreations500ResponseErrorsInner } from './apps-list-org-creations500-response-errors-inner';
import { AppsListOrgCreations500ResponseJsonapi } from './apps-list-org-creations500-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListOrgCreations500Response
 */
export interface AppsListOrgCreations500Response {
    /**
     * 
     * @type {Array<AppsListOrgCreations500ResponseErrorsInner>}
     * @memberof AppsListOrgCreations500Response
     */
    'errors': Array<AppsListOrgCreations500ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListOrgCreations500ResponseJsonapi}
     * @memberof AppsListOrgCreations500Response
     */
    'jsonapi': AppsListOrgCreations500ResponseJsonapi;
}

