/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsInstallSnykAppToOrg403ResponseErrorsInner } from './apps-install-snyk-app-to-org403-response-errors-inner';
import { AppsInstallSnykAppToOrg403ResponseJsonapi } from './apps-install-snyk-app-to-org403-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsInstallSnykAppToOrg403Response
 */
export interface AppsInstallSnykAppToOrg403Response {
    /**
     * 
     * @type {Array<AppsInstallSnykAppToOrg403ResponseErrorsInner>}
     * @memberof AppsInstallSnykAppToOrg403Response
     */
    'errors': Array<AppsInstallSnykAppToOrg403ResponseErrorsInner>;
    /**
     * 
     * @type {AppsInstallSnykAppToOrg403ResponseJsonapi}
     * @memberof AppsInstallSnykAppToOrg403Response
     */
    'jsonapi': AppsInstallSnykAppToOrg403ResponseJsonapi;
}

