/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsRevokeGroupAppInstall404ResponseErrorsInner } from './apps-revoke-group-app-install404-response-errors-inner';
import { AppsRevokeGroupAppInstall404ResponseJsonapi } from './apps-revoke-group-app-install404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsRevokeGroupAppInstall404Response
 */
export interface AppsRevokeGroupAppInstall404Response {
    /**
     * 
     * @type {Array<AppsRevokeGroupAppInstall404ResponseErrorsInner>}
     * @memberof AppsRevokeGroupAppInstall404Response
     */
    'errors': Array<AppsRevokeGroupAppInstall404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsRevokeGroupAppInstall404ResponseJsonapi}
     * @memberof AppsRevokeGroupAppInstall404Response
     */
    'jsonapi': AppsRevokeGroupAppInstall404ResponseJsonapi;
}

