/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsRevokeUserAppSessionResponseErrorsInner } from './apps-revoke-user-app-session-response-errors-inner';
import { AppsRevokeUserAppSessionResponseJsonapi } from './apps-revoke-user-app-session-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsRevokeUserAppSessionResponse
 */
export interface AppsRevokeUserAppSessionResponse {
    /**
     * 
     * @type {Array<AppsRevokeUserAppSessionResponseErrorsInner>}
     * @memberof AppsRevokeUserAppSessionResponse
     */
    'errors': Array<AppsRevokeUserAppSessionResponseErrorsInner>;
    /**
     * 
     * @type {AppsRevokeUserAppSessionResponseJsonapi}
     * @memberof AppsRevokeUserAppSessionResponse
     */
    'jsonapi': AppsRevokeUserAppSessionResponseJsonapi;
}

