/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsManageClientSecrets401ResponseErrorsInner } from './apps-manage-client-secrets401-response-errors-inner';
import { AppsManageClientSecrets401ResponseJsonapi } from './apps-manage-client-secrets401-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsManageClientSecrets401Response
 */
export interface AppsManageClientSecrets401Response {
    /**
     * 
     * @type {Array<AppsManageClientSecrets401ResponseErrorsInner>}
     * @memberof AppsManageClientSecrets401Response
     */
    'errors': Array<AppsManageClientSecrets401ResponseErrorsInner>;
    /**
     * 
     * @type {AppsManageClientSecrets401ResponseJsonapi}
     * @memberof AppsManageClientSecrets401Response
     */
    'jsonapi': AppsManageClientSecrets401ResponseJsonapi;
}

