/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListApps404ResponseErrorsInner } from './apps-list-apps404-response-errors-inner';
import { AppsListApps404ResponseJsonapi } from './apps-list-apps404-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListApps404Response
 */
export interface AppsListApps404Response {
    /**
     * 
     * @type {Array<AppsListApps404ResponseErrorsInner>}
     * @memberof AppsListApps404Response
     */
    'errors': Array<AppsListApps404ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListApps404ResponseJsonapi}
     * @memberof AppsListApps404Response
     */
    'jsonapi': AppsListApps404ResponseJsonapi;
}

