/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListGroupAppInstalls401ResponseErrorsInner } from './apps-list-group-app-installs401-response-errors-inner';
import { AppsListGroupAppInstalls401ResponseJsonapi } from './apps-list-group-app-installs401-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListGroupAppInstalls401Response
 */
export interface AppsListGroupAppInstalls401Response {
    /**
     * 
     * @type {Array<AppsListGroupAppInstalls401ResponseErrorsInner>}
     * @memberof AppsListGroupAppInstalls401Response
     */
    'errors': Array<AppsListGroupAppInstalls401ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListGroupAppInstalls401ResponseJsonapi}
     * @memberof AppsListGroupAppInstalls401Response
     */
    'jsonapi': AppsListGroupAppInstalls401ResponseJsonapi;
}

