/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsDeleteByAppId401ResponseErrorsInner } from './apps-delete-by-app-id401-response-errors-inner';
import { AppsDeleteByAppId401ResponseJsonapi } from './apps-delete-by-app-id401-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsDeleteByAppId401Response
 */
export interface AppsDeleteByAppId401Response {
    /**
     * 
     * @type {Array<AppsDeleteByAppId401ResponseErrorsInner>}
     * @memberof AppsDeleteByAppId401Response
     */
    'errors': Array<AppsDeleteByAppId401ResponseErrorsInner>;
    /**
     * 
     * @type {AppsDeleteByAppId401ResponseJsonapi}
     * @memberof AppsDeleteByAppId401Response
     */
    'jsonapi': AppsDeleteByAppId401ResponseJsonapi;
}

