/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppsGetByClientId409ResponseJsonapi
 */
export interface AppsGetByClientId409ResponseJsonapi {
    /**
     * Version of the JSON API specification this server supports.
     * @type {string}
     * @memberof AppsGetByClientId409ResponseJsonapi
     */
    'version': string;
}

