/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsDeleteByAppId403ResponseErrorsInner } from './apps-delete-by-app-id403-response-errors-inner';
import { AppsDeleteByAppId403ResponseJsonapi } from './apps-delete-by-app-id403-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsDeleteByAppId403Response
 */
export interface AppsDeleteByAppId403Response {
    /**
     * 
     * @type {Array<AppsDeleteByAppId403ResponseErrorsInner>}
     * @memberof AppsDeleteByAppId403Response
     */
    'errors': Array<AppsDeleteByAppId403ResponseErrorsInner>;
    /**
     * 
     * @type {AppsDeleteByAppId403ResponseJsonapi}
     * @memberof AppsDeleteByAppId403Response
     */
    'jsonapi': AppsDeleteByAppId403ResponseJsonapi;
}

