/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsByInstallId500ResponseErrorsInner } from './apps-by-install-id500-response-errors-inner';
import { AppsByInstallId500ResponseJsonapi } from './apps-by-install-id500-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsByInstallId500Response
 */
export interface AppsByInstallId500Response {
    /**
     * 
     * @type {Array<AppsByInstallId500ResponseErrorsInner>}
     * @memberof AppsByInstallId500Response
     */
    'errors': Array<AppsByInstallId500ResponseErrorsInner>;
    /**
     * 
     * @type {AppsByInstallId500ResponseJsonapi}
     * @memberof AppsByInstallId500Response
     */
    'jsonapi': AppsByInstallId500ResponseJsonapi;
}

