/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsUpdateAttributes500ResponseErrorsInner } from './apps-update-attributes500-response-errors-inner';
import { AppsUpdateAttributes500ResponseJsonapi } from './apps-update-attributes500-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsUpdateAttributes500Response
 */
export interface AppsUpdateAttributes500Response {
    /**
     * 
     * @type {Array<AppsUpdateAttributes500ResponseErrorsInner>}
     * @memberof AppsUpdateAttributes500Response
     */
    'errors': Array<AppsUpdateAttributes500ResponseErrorsInner>;
    /**
     * 
     * @type {AppsUpdateAttributes500ResponseJsonapi}
     * @memberof AppsUpdateAttributes500Response
     */
    'jsonapi': AppsUpdateAttributes500ResponseJsonapi;
}

