/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsCreateInstallSecret500ResponseErrorsInner } from './apps-create-install-secret500-response-errors-inner';
import { AppsCreateInstallSecret500ResponseJsonapi } from './apps-create-install-secret500-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsCreateInstallSecret500Response
 */
export interface AppsCreateInstallSecret500Response {
    /**
     * 
     * @type {Array<AppsCreateInstallSecret500ResponseErrorsInner>}
     * @memberof AppsCreateInstallSecret500Response
     */
    'errors': Array<AppsCreateInstallSecret500ResponseErrorsInner>;
    /**
     * 
     * @type {AppsCreateInstallSecret500ResponseJsonapi}
     * @memberof AppsCreateInstallSecret500Response
     */
    'jsonapi': AppsCreateInstallSecret500ResponseJsonapi;
}

