/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppsListAppBots400ResponseErrorsInner } from './apps-list-app-bots400-response-errors-inner';
import { AppsListAppBots400ResponseJsonapi } from './apps-list-app-bots400-response-jsonapi';

/**
 * 
 * @export
 * @interface AppsListAppBots400Response
 */
export interface AppsListAppBots400Response {
    /**
     * 
     * @type {Array<AppsListAppBots400ResponseErrorsInner>}
     * @memberof AppsListAppBots400Response
     */
    'errors': Array<AppsListAppBots400ResponseErrorsInner>;
    /**
     * 
     * @type {AppsListAppBots400ResponseJsonapi}
     * @memberof AppsListAppBots400Response
     */
    'jsonapi': AppsListAppBots400ResponseJsonapi;
}

