/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuditLogSearch } from './audit-log-search';
import { JsonApi } from './json-api';
import { Links } from './links';

/**
 * 
 * @export
 * @interface AuditLogsSearchOrganizationAuditLogsResponse
 */
export interface AuditLogsSearchOrganizationAuditLogsResponse {
    /**
     * 
     * @type {AuditLogSearch}
     * @memberof AuditLogsSearchOrganizationAuditLogsResponse
     */
    'data': AuditLogSearch;
    /**
     * 
     * @type {JsonApi}
     * @memberof AuditLogsSearchOrganizationAuditLogsResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {Links}
     * @memberof AuditLogsSearchOrganizationAuditLogsResponse
     */
    'links'?: Links;
}

