/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Automatically create pull requests on recurring tests for dependencies as upgrades become available. If not specified, settings will be inherited from the Project\'s integration.
 * @export
 * @interface AutoDependencyUpgradeSettings
 */
export interface AutoDependencyUpgradeSettings {
    /**
     * Dependencies which should NOT be included in an automatic upgrade operation.
     * @type {Array<string>}
     * @memberof AutoDependencyUpgradeSettings
     */
    'ignored_dependencies'?: Array<string>;
    /**
     * Automatically raise pull requests to update out-of-date dependencies.
     * @type {boolean}
     * @memberof AutoDependencyUpgradeSettings
     */
    'is_enabled'?: boolean;
    /**
     * Apply the auto dependency integration settings of the Organization to this project.
     * @type {boolean}
     * @memberof AutoDependencyUpgradeSettings
     */
    'is_inherited'?: boolean;
    /**
     * Include major version in dependency upgrade recommendation.
     * @type {boolean}
     * @memberof AutoDependencyUpgradeSettings
     */
    'is_major_upgrade_enabled'?: boolean;
    /**
     * Limit of dependency upgrade PRs which can be opened simultaneously. When the limit is reached, no new upgrade PRs are created. If specified, must be between 1 and 10.
     * @type {number}
     * @memberof AutoDependencyUpgradeSettings
     */
    'limit'?: number;
    /**
     * Minimum dependency maturity period in days. If specified, must be between 1 and 365.
     * @type {number}
     * @memberof AutoDependencyUpgradeSettings
     */
    'minimum_age'?: number;
}

