/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ClassTypeDef } from './class-type-def';

/**
 * 
 * @export
 * @interface Class
 */
export interface Class {
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof Class
     */
    'source': string;
    /**
     * 
     * @type {ClassTypeDef}
     * @memberof Class
     */
    'type': ClassTypeDef;
    /**
     * An optional URL for this class.
     * @type {string}
     * @memberof Class
     */
    'url'?: string;
}

