/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollectionRelationshipsCreatedByUser } from './collection-relationships-created-by-user';
import { CollectionRelationshipsOrg } from './collection-relationships-org';

/**
 * 
 * @export
 * @interface CollectionRelationships
 */
export interface CollectionRelationships {
    /**
     * 
     * @type {CollectionRelationshipsCreatedByUser}
     * @memberof CollectionRelationships
     */
    'created_by_user': CollectionRelationshipsCreatedByUser;
    /**
     * 
     * @type {CollectionRelationshipsOrg}
     * @memberof CollectionRelationships
     */
    'org': CollectionRelationshipsOrg;
}

