/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CollectionRelationshipsOrgData
 */
export interface CollectionRelationshipsOrgData {
    /**
     * ID of the org that this collection belongs to
     * @type {string}
     * @memberof CollectionRelationshipsOrgData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CollectionRelationshipsOrgData
     */
    'type': CollectionRelationshipsOrgDataTypeEnum;
}

type CollectionRelationshipsOrgDataTypeEnum = 'org'


