/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollectionRelationshipsCreatedByUserData } from './collection-relationships-created-by-user-data';

/**
 * 
 * @export
 * @interface CollectionRelationshipsCreatedByUser
 */
export interface CollectionRelationshipsCreatedByUser {
    /**
     * 
     * @type {CollectionRelationshipsCreatedByUserData}
     * @memberof CollectionRelationshipsCreatedByUser
     */
    'data': CollectionRelationshipsCreatedByUserData;
}

