/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CollectionCreateNewResponseData } from './collection-create-new-response-data';
import { JsonApi } from './json-api';
import { SelfLink } from './self-link';

/**
 * 
 * @export
 * @interface CollectionGetByIdResponse
 */
export interface CollectionGetByIdResponse {
    /**
     * 
     * @type {CollectionCreateNewResponseData}
     * @memberof CollectionGetByIdResponse
     */
    'data'?: CollectionCreateNewResponseData;
    /**
     * 
     * @type {JsonApi}
     * @memberof CollectionGetByIdResponse
     */
    'jsonapi'?: JsonApi;
    /**
     * 
     * @type {SelfLink}
     * @memberof CollectionGetByIdResponse
     */
    'links'?: SelfLink;
}

