/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CommonIssueModelVTwoAttributesProblemsInner
 */
export interface CommonIssueModelVTwoAttributesProblemsInner {
    /**
     * When this problem was disclosed to the public.
     * @type {string}
     * @memberof CommonIssueModelVTwoAttributesProblemsInner
     */
    'disclosed_at'?: string;
    /**
     * When this problem was first discovered.
     * @type {string}
     * @memberof CommonIssueModelVTwoAttributesProblemsInner
     */
    'discovered_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonIssueModelVTwoAttributesProblemsInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CommonIssueModelVTwoAttributesProblemsInner
     */
    'source': string;
    /**
     * When this problem was last updated.
     * @type {string}
     * @memberof CommonIssueModelVTwoAttributesProblemsInner
     */
    'updated_at'?: string;
    /**
     * An optional URL for this problem.
     * @type {string}
     * @memberof CommonIssueModelVTwoAttributesProblemsInner
     */
    'url'?: string;
}

