/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommonIssueModelAttributesCoordinatesInnerRemediesInner } from './common-issue-model-attributes-coordinates-inner-remedies-inner';

/**
 * 
 * @export
 * @interface CommonIssueModelAttributesCoordinatesInner
 */
export interface CommonIssueModelAttributesCoordinatesInner {
    /**
     * 
     * @type {Array<CommonIssueModelAttributesCoordinatesInnerRemediesInner>}
     * @memberof CommonIssueModelAttributesCoordinatesInner
     */
    'remedies'?: Array<CommonIssueModelAttributesCoordinatesInnerRemediesInner>;
    /**
     * The affected versions of this vulnerability.
     * @type {Array<string>}
     * @memberof CommonIssueModelAttributesCoordinatesInner
     */
    'representation'?: Array<string>;
}

