/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CommonIssueModelVTwoAttributes } from './common-issue-model-vtwo-attributes';

/**
 * 
 * @export
 * @interface CommonIssueModelVTwo
 */
export interface CommonIssueModelVTwo {
    /**
     * 
     * @type {CommonIssueModelVTwoAttributes}
     * @memberof CommonIssueModelVTwo
     */
    'attributes'?: CommonIssueModelVTwoAttributes;
    /**
     * The Snyk ID of the vulnerability.
     * @type {string}
     * @memberof CommonIssueModelVTwo
     */
    'id'?: string;
    /**
     * The type of the REST resource. Always ‘issue’.
     * @type {string}
     * @memberof CommonIssueModelVTwo
     */
    'type'?: string;
}

