/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ImageTargetRef } from './image-target-ref';
import { JsonApi } from './json-api';
import { PaginatedLinks } from './paginated-links';

/**
 * 
 * @export
 * @interface ContainerImageListImageTargetRefsResponse
 */
export interface ContainerImageListImageTargetRefsResponse {
    /**
     * 
     * @type {Array<ImageTargetRef>}
     * @memberof ContainerImageListImageTargetRefsResponse
     */
    'data'?: Array<ImageTargetRef>;
    /**
     * 
     * @type {JsonApi}
     * @memberof ContainerImageListImageTargetRefsResponse
     */
    'jsonapi'?: JsonApi;
    /**
     * 
     * @type {PaginatedLinks}
     * @memberof ContainerImageListImageTargetRefsResponse
     */
    'links'?: PaginatedLinks;
}

