/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Image } from './image';
import { JsonApi } from './json-api';
import { SelfLink } from './self-link';

/**
 * 
 * @export
 * @interface ContainerImageGetInstanceResponse
 */
export interface ContainerImageGetInstanceResponse {
    /**
     * 
     * @type {Image}
     * @memberof ContainerImageGetInstanceResponse
     */
    'data'?: Image;
    /**
     * 
     * @type {JsonApi}
     * @memberof ContainerImageGetInstanceResponse
     */
    'jsonapi'?: JsonApi;
    /**
     * 
     * @type {SelfLink}
     * @memberof ContainerImageGetInstanceResponse
     */
    'links'?: SelfLink;
}

