/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CoordinateVTwoRemediesInnerDetails
 */
export interface CoordinateVTwoRemediesInnerDetails {
    /**
     * A minimum version to upgrade to in order to remedy the issue.
     * @type {string}
     * @memberof CoordinateVTwoRemediesInnerDetails
     */
    'upgrade_package'?: string;
}

