/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Dependency } from './dependency';

/**
 * An object that contains a list of opaque identifying strings.
 * @export
 * @interface CoordinateRepresentationsInnerOneOf1
 */
export interface CoordinateRepresentationsInnerOneOf1 {
    /**
     * 
     * @type {Dependency}
     * @memberof CoordinateRepresentationsInnerOneOf1
     */
    'dependency': Dependency;
}

