/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CloudResource } from './cloud-resource';

/**
 * A resource location to some service, like a cloud resource.
 * @export
 * @interface CoordinateRepresentationsInnerOneOf2
 */
export interface CoordinateRepresentationsInnerOneOf2 {
    /**
     * 
     * @type {CloudResource}
     * @memberof CoordinateRepresentationsInnerOneOf2
     */
    'cloud_resource': CloudResource;
}

