/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SourceLocation } from './source-location';

/**
 * A location within a file.
 * @export
 * @interface CoordinateRepresentationsInnerOneOf3
 */
export interface CoordinateRepresentationsInnerOneOf3 {
    /**
     * 
     * @type {SourceLocation}
     * @memberof CoordinateRepresentationsInnerOneOf3
     */
    'sourceLocation': SourceLocation;
}

