/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateCollectionRequestDataAttributes
 */
export interface CreateCollectionRequestDataAttributes {
    /**
     * User-defined name of the collection
     * @type {string}
     * @memberof CreateCollectionRequestDataAttributes
     */
    'name': string;
}

