/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { VersioningSchema } from './versioning-schema';

/**
 * 
 * @export
 * @interface CustomBaseImageAttributes
 */
export interface CustomBaseImageAttributes {
    /**
     * Whether this image should be recommended as a base image upgrade.  If set to true, this image could be shown as a base image upgrade to other projects. If set to false this image will never be recommended as an upgrade. 
     * @type {boolean}
     * @memberof CustomBaseImageAttributes
     */
    'include_in_recommendations': boolean;
    /**
     * The ID of the container project that the custom base image is based off of. The attributes of this custom base image are taken from the latest snapshot at the time of creation. This means that no changes should be made to the original project after the creation of the custom base image, as new snapshots created from any changes will NOT be picked up. 
     * @type {string}
     * @memberof CustomBaseImageAttributes
     */
    'project_id': string;
    /**
     * 
     * @type {VersioningSchema}
     * @memberof CustomBaseImageAttributes
     */
    'versioning_schema'?: VersioningSchema;
}

