/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CustomBaseImageSnapshot
 */
export interface CustomBaseImageSnapshot {
    /**
     * 
     * @type {string}
     * @memberof CustomBaseImageSnapshot
     */
    'group_id'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomBaseImageSnapshot
     */
    'include_in_recommendations'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomBaseImageSnapshot
     */
    'org_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomBaseImageSnapshot
     */
    'project_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomBaseImageSnapshot
     */
    'repository'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomBaseImageSnapshot
     */
    'tag'?: string;
}

