/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CycloneDxTool
 */
export interface CycloneDxTool {
    /**
     * 
     * @type {string}
     * @memberof CycloneDxTool
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CycloneDxTool
     */
    'vendor'?: string;
}

