/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CycloneDxDependency
 */
export interface CycloneDxDependency {
    /**
     * 
     * @type {Array<string>}
     * @memberof CycloneDxDependency
     */
    'dependsOn'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CycloneDxDependency
     */
    'ref'?: string;
}

