/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CycloneDxProperty
 */
export interface CycloneDxProperty {
    /**
     * 
     * @type {string}
     * @memberof CycloneDxProperty
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CycloneDxProperty
     */
    'value'?: string;
}

