/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DeleteProjectsFromCollectionRequestDataInner
 */
export interface DeleteProjectsFromCollectionRequestDataInner {
    /**
     * 
     * @type {string}
     * @memberof DeleteProjectsFromCollectionRequestDataInner
     */
    'id': string;
    /**
     * Type of the item id
     * @type {string}
     * @memberof DeleteProjectsFromCollectionRequestDataInner
     */
    'type': DeleteProjectsFromCollectionRequestDataInnerTypeEnum;
}

type DeleteProjectsFromCollectionRequestDataInnerTypeEnum = 'project'


