/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DeleteProjectsFromCollectionRequestDataInner } from './delete-projects-from-collection-request-data-inner';

/**
 * 
 * @export
 * @interface DeleteProjectsFromCollectionRequest
 */
export interface DeleteProjectsFromCollectionRequest {
    /**
     * IDs of items to remove from a collection
     * @type {Array<DeleteProjectsFromCollectionRequestDataInner>}
     * @memberof DeleteProjectsFromCollectionRequest
     */
    'data': Array<DeleteProjectsFromCollectionRequestDataInner>;
}

