/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';

/**
 * 
 * @export
 * @interface ErrorDocument
 */
export interface ErrorDocument {
    /**
     * 
     * @type {Array<Error>}
     * @memberof ErrorDocument
     */
    'errors': Array<Error>;
    /**
     * 
     * @type {JsonApi}
     * @memberof ErrorDocument
     */
    'jsonapi': JsonApi;
}

