/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An authorization grant is a credential representing the resource owner\'s authorization (to access its protected resources) used by the client to obtain an access token. The grant type represents the way your app will get the access token.
 * @export
 * @enum {string}
 */
export type GrantType = 'authorization_code' | 'client_credentials'

