/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupIacSettingsRequestAttributes } from './group-iac-settings-request-attributes';

/**
 * The Infrastructure as Code settings for a group.
 * @export
 * @interface GroupIacSettingsRequest
 */
export interface GroupIacSettingsRequest {
    /**
     * 
     * @type {GroupIacSettingsRequestAttributes}
     * @memberof GroupIacSettingsRequest
     */
    'attributes': GroupIacSettingsRequestAttributes;
    /**
     * Content type
     * @type {string}
     * @memberof GroupIacSettingsRequest
     */
    'type': string;
}

