/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupIacSettingsRequestAttributesCustomRules } from './group-iac-settings-request-attributes-custom-rules';

/**
 * 
 * @export
 * @interface GroupIacSettingsRequestAttributes
 */
export interface GroupIacSettingsRequestAttributes {
    /**
     * 
     * @type {GroupIacSettingsRequestAttributesCustomRules}
     * @memberof GroupIacSettingsRequestAttributes
     */
    'custom_rules'?: GroupIacSettingsRequestAttributesCustomRules;
}

