/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupIacSettingsResponseAttributesCustomRules } from './group-iac-settings-response-attributes-custom-rules';

/**
 * 
 * @export
 * @interface GroupIacSettingsResponseAttributes
 */
export interface GroupIacSettingsResponseAttributes {
    /**
     * 
     * @type {GroupIacSettingsResponseAttributesCustomRules}
     * @memberof GroupIacSettingsResponseAttributes
     */
    'custom_rules'?: GroupIacSettingsResponseAttributesCustomRules;
    /**
     * The last time the settings were updated.
     * @type {string}
     * @memberof GroupIacSettingsResponseAttributes
     */
    'updated'?: string;
}

