/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HelloWorldAttributes } from './hello-world-attributes';

/**
 * 
 * @export
 * @interface HelloWorld
 */
export interface HelloWorld {
    /**
     * 
     * @type {HelloWorldAttributes}
     * @memberof HelloWorld
     */
    'attributes': HelloWorldAttributes;
    /**
     * 
     * @type {string}
     * @memberof HelloWorld
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof HelloWorld
     */
    'type': string;
}

