/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupIacSettingsRequest } from './group-iac-settings-request';

/**
 * 
 * @export
 * @interface IacSettingsUpdateForGroupRequest
 */
export interface IacSettingsUpdateForGroupRequest {
    /**
     * 
     * @type {GroupIacSettingsRequest}
     * @memberof IacSettingsUpdateForGroupRequest
     */
    'data'?: GroupIacSettingsRequest;
}

