/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';
import { Links } from './links';
import { OrgInvitation } from './org-invitation';

/**
 * 
 * @export
 * @interface InvitesListPendingUserInvitationsResponse
 */
export interface InvitesListPendingUserInvitationsResponse {
    /**
     * 
     * @type {Array<OrgInvitation>}
     * @memberof InvitesListPendingUserInvitationsResponse
     */
    'data': Array<OrgInvitation>;
    /**
     * 
     * @type {JsonApi}
     * @memberof InvitesListPendingUserInvitationsResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {Links}
     * @memberof InvitesListPendingUserInvitationsResponse
     */
    'links': Links;
}

