/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IssueRelationshipsIgnore } from './issue-relationships-ignore';
import { IssueRelationshipsOrganization } from './issue-relationships-organization';
import { IssueRelationshipsScanItem } from './issue-relationships-scan-item';
import { IssueRelationshipsTestExecutions } from './issue-relationships-test-executions';

/**
 * issue relationships
 * @export
 * @interface IssueRelationships
 */
export interface IssueRelationships {
    /**
     * 
     * @type {IssueRelationshipsIgnore}
     * @memberof IssueRelationships
     */
    'ignore'?: IssueRelationshipsIgnore;
    /**
     * 
     * @type {IssueRelationshipsOrganization}
     * @memberof IssueRelationships
     */
    'organization': IssueRelationshipsOrganization;
    /**
     * 
     * @type {IssueRelationshipsScanItem}
     * @memberof IssueRelationships
     */
    'scan_item': IssueRelationshipsScanItem;
    /**
     * 
     * @type {IssueRelationshipsTestExecutions}
     * @memberof IssueRelationships
     */
    'test_executions'?: IssueRelationshipsTestExecutions;
}

