/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IssuesGetByIssueId404ResponseErrorsInner } from './issues-get-by-issue-id404-response-errors-inner';
import { IssuesGetByIssueId404ResponseJsonapi } from './issues-get-by-issue-id404-response-jsonapi';

/**
 * 
 * @export
 * @interface IssuesGetByIssueId404Response
 */
export interface IssuesGetByIssueId404Response {
    /**
     * 
     * @type {Array<IssuesGetByIssueId404ResponseErrorsInner>}
     * @memberof IssuesGetByIssueId404Response
     */
    'errors': Array<IssuesGetByIssueId404ResponseErrorsInner>;
    /**
     * 
     * @type {IssuesGetByIssueId404ResponseJsonapi}
     * @memberof IssuesGetByIssueId404Response
     */
    'jsonapi': IssuesGetByIssueId404ResponseJsonapi;
}

