/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { IssuesGetByIssueId409ResponseErrorsInner } from './issues-get-by-issue-id409-response-errors-inner';
import { IssuesGetByIssueId409ResponseJsonapi } from './issues-get-by-issue-id409-response-jsonapi';

/**
 * 
 * @export
 * @interface IssuesGetByIssueId409Response
 */
export interface IssuesGetByIssueId409Response {
    /**
     * 
     * @type {Array<IssuesGetByIssueId409ResponseErrorsInner>}
     * @memberof IssuesGetByIssueId409Response
     */
    'errors': Array<IssuesGetByIssueId409ResponseErrorsInner>;
    /**
     * 
     * @type {IssuesGetByIssueId409ResponseJsonapi}
     * @memberof IssuesGetByIssueId409Response
     */
    'jsonapi': IssuesGetByIssueId409ResponseJsonapi;
}

