/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LatestIssueCounts
 */
export interface LatestIssueCounts {
    /**
     * 
     * @type {number}
     * @memberof LatestIssueCounts
     */
    'critical'?: number;
    /**
     * 
     * @type {number}
     * @memberof LatestIssueCounts
     */
    'high'?: number;
    /**
     * 
     * @type {number}
     * @memberof LatestIssueCounts
     */
    'low'?: number;
    /**
     * 
     * @type {number}
     * @memberof LatestIssueCounts
     */
    'medium'?: number;
    /**
     * 
     * @type {string}
     * @memberof LatestIssueCounts
     */
    'updated_at'?: string;
}

