/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Manually raise pull requests to fix new and existing vulnerabilities. If not specified, settings will be inherited from the Project\'s integration.
 * @export
 * @interface ManualRemediationPRsSettings
 */
export interface ManualRemediationPRsSettings {
    /**
     * Include vulnerability patches in manual pull requests.
     * @type {boolean}
     * @memberof ManualRemediationPRsSettings
     */
    'is_patch_remediation_enabled'?: boolean;
}

