/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrgRoleAttributes } from './org-role-attributes';

/**
 * 
 * @export
 * @interface MemberRoleRelationshipData
 */
export interface MemberRoleRelationshipData {
    /**
     * 
     * @type {OrgRoleAttributes}
     * @memberof MemberRoleRelationshipData
     */
    'attributes'?: OrgRoleAttributes;
    /**
     * The Snyk ID of the organization role.
     * @type {string}
     * @memberof MemberRoleRelationshipData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MemberRoleRelationshipData
     */
    'type': string;
}

