/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OrgInvitationAttributes
 */
export interface OrgInvitationAttributes {
    /**
     * The email address of the invitee.
     * @type {string}
     * @memberof OrgInvitationAttributes
     */
    'email': string;
    /**
     * The active status of the invitation. is_active of true indicates that the invitation is still waiting to be accepted. Invitations are considered inactive when accepted or revoked. 
     * @type {boolean}
     * @memberof OrgInvitationAttributes
     */
    'is_active': boolean;
    /**
     * The role public ID that will be granted to to invitee on acceptance.
     * @type {string}
     * @memberof OrgInvitationAttributes
     */
    'role': string;
}

