/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GroupIacSettingsResponseAttributesCustomRules } from './group-iac-settings-response-attributes-custom-rules';

/**
 * The Infrastructure as Code settings at the group level.
 * @export
 * @interface OrgIacSettingsResponseAttributesCustomRulesParentsGroup
 */
export interface OrgIacSettingsResponseAttributesCustomRulesParentsGroup {
    /**
     * 
     * @type {GroupIacSettingsResponseAttributesCustomRules}
     * @memberof OrgIacSettingsResponseAttributesCustomRulesParentsGroup
     */
    'custom_rules'?: GroupIacSettingsResponseAttributesCustomRules;
    /**
     * The last time the settings were updated.
     * @type {string}
     * @memberof OrgIacSettingsResponseAttributesCustomRulesParentsGroup
     */
    'updated'?: string;
}

