/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OrgInvitationPostAttributes
 */
export interface OrgInvitationPostAttributes {
    /**
     * The email address of the invitee.
     * @type {string}
     * @memberof OrgInvitationPostAttributes
     */
    'email': string;
    /**
     * The role public ID that will be granted to to invitee on acceptance.
     * @type {any}
     * @memberof OrgInvitationPostAttributes
     */
    'role': any;
}

