/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrgIacSettingsResponseAttributesCustomRules } from './org-iac-settings-response-attributes-custom-rules';

/**
 * 
 * @export
 * @interface OrgIacSettingsResponseAttributes
 */
export interface OrgIacSettingsResponseAttributes {
    /**
     * 
     * @type {OrgIacSettingsResponseAttributesCustomRules}
     * @memberof OrgIacSettingsResponseAttributes
     */
    'custom_rules'?: OrgIacSettingsResponseAttributesCustomRules;
}

