/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Relationship } from './relationship';

/**
 * 
 * @export
 * @interface OrgInvitationRelationships
 */
export interface OrgInvitationRelationships {
    /**
     * 
     * @type {Relationship}
     * @memberof OrgInvitationRelationships
     */
    'org'?: Relationship;
}

