/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrgInvitationAttributes } from './org-invitation-attributes';
import { OrgInvitationRelationships } from './org-invitation-relationships';

/**
 * 
 * @export
 * @interface OrgInvitation
 */
export interface OrgInvitation {
    /**
     * 
     * @type {OrgInvitationAttributes}
     * @memberof OrgInvitation
     */
    'attributes': OrgInvitationAttributes;
    /**
     * 
     * @type {string}
     * @memberof OrgInvitation
     */
    'id': string;
    /**
     * 
     * @type {OrgInvitationRelationships}
     * @memberof OrgInvitation
     */
    'relationships'?: OrgInvitationRelationships;
    /**
     * 
     * @type {string}
     * @memberof OrgInvitation
     */
    'type': OrgInvitationTypeEnum;
}

type OrgInvitationTypeEnum = 'org_invitation'


