/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrgAttributes } from './org-attributes';
import { OrgRelationships } from './org-relationships';

/**
 * org resource object
 * @export
 * @interface OrgsUpdateDetailsResponseData
 */
export interface OrgsUpdateDetailsResponseData {
    /**
     * 
     * @type {OrgAttributes}
     * @memberof OrgsUpdateDetailsResponseData
     */
    'attributes'?: OrgAttributes;
    /**
     * 
     * @type {string}
     * @memberof OrgsUpdateDetailsResponseData
     */
    'id': string;
    /**
     * 
     * @type {OrgRelationships}
     * @memberof OrgsUpdateDetailsResponseData
     */
    'relationships'?: OrgRelationships;
    /**
     * 
     * @type {string}
     * @memberof OrgsUpdateDetailsResponseData
     */
    'type': string;
}

