/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';
import { OrgWithRelationships } from './org-with-relationships';
import { PaginatedLinks } from './paginated-links';

/**
 * 
 * @export
 * @interface OrgsListAccessibleOrganizationsResponse
 */
export interface OrgsListAccessibleOrganizationsResponse {
    /**
     * 
     * @type {Array<OrgWithRelationships>}
     * @memberof OrgsListAccessibleOrganizationsResponse
     */
    'data': Array<OrgWithRelationships>;
    /**
     * 
     * @type {JsonApi}
     * @memberof OrgsListAccessibleOrganizationsResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {PaginatedLinks}
     * @memberof OrgsListAccessibleOrganizationsResponse
     */
    'links': PaginatedLinks;
}

