/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PackageMeta
 */
export interface PackageMeta {
    /**
     * The version of the package
     * @type {string}
     * @memberof PackageMeta
     */
    'version'?: string;
    /**
     * The package’s name
     * @type {string}
     * @memberof PackageMeta
     */
    'name'?: string;
    /**
     * A name prefix, such as a maven group id or docker image owner
     * @type {string}
     * @memberof PackageMeta
     */
    'namespace'?: string;
    /**
     * The package type or protocol
     * @type {string}
     * @memberof PackageMeta
     */
    'type'?: string;
    /**
     * The purl of the package
     * @type {string}
     * @memberof PackageMeta
     */
    'url'?: string;
}

