/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsGetByProjectIdResponseDataRelationshipsOwnerLinksRelated } from './projects-get-by-project-id-response-data-relationships-owner-links-related';

/**
 * 
 * @export
 * @interface ProjectsGetByProjectIdResponseDataRelationshipsOwnerLinks
 */
export interface ProjectsGetByProjectIdResponseDataRelationshipsOwnerLinks {
    /**
     * 
     * @type {ProjectsGetByProjectIdResponseDataRelationshipsOwnerLinksRelated}
     * @memberof ProjectsGetByProjectIdResponseDataRelationshipsOwnerLinks
     */
    'related'?: ProjectsGetByProjectIdResponseDataRelationshipsOwnerLinksRelated;
}

