/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf } from './projects-list-for-org-response-data-inner-relationships-target-one-of';
import { ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf1 } from './projects-list-for-org-response-data-inner-relationships-target-one-of1';
import { ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf1Data } from './projects-list-for-org-response-data-inner-relationships-target-one-of1-data';
import { ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf1Links } from './projects-list-for-org-response-data-inner-relationships-target-one-of1-links';

/**
 * @type ProjectsListForOrgResponseDataInnerRelationshipsTarget
 * @export
 */
export type ProjectsListForOrgResponseDataInnerRelationshipsTarget = ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf | ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf1;


