/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinksRelated } from './projects-list-for-org-response-data-inner-relationships-owner-links-related';

/**
 * 
 * @export
 * @interface ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks
 */
export interface ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks {
    /**
     * 
     * @type {ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinksRelated}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks
     */
    'related'?: ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinksRelated;
}

