/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';
import { Links } from './links';
import { ProjectsListForOrgResponseDataInner } from './projects-list-for-org-response-data-inner';
import { ProjectsListForOrgResponseMeta } from './projects-list-for-org-response-meta';

/**
 * 
 * @export
 * @interface ProjectsListForOrgResponse
 */
export interface ProjectsListForOrgResponse {
    /**
     * 
     * @type {Array<ProjectsListForOrgResponseDataInner>}
     * @memberof ProjectsListForOrgResponse
     */
    'data'?: Array<ProjectsListForOrgResponseDataInner>;
    /**
     * 
     * @type {JsonApi}
     * @memberof ProjectsListForOrgResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {Links}
     * @memberof ProjectsListForOrgResponse
     */
    'links': Links;
    /**
     * 
     * @type {ProjectsListForOrgResponseMeta}
     * @memberof ProjectsListForOrgResponse
     */
    'meta'?: ProjectsListForOrgResponseMeta;
}

