/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf } from './projects-update-by-project-id-response-data-relationships-target-one-of';
import { ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf1 } from './projects-update-by-project-id-response-data-relationships-target-one-of1';
import { ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf1Data } from './projects-update-by-project-id-response-data-relationships-target-one-of1-data';
import { ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf1Links } from './projects-update-by-project-id-response-data-relationships-target-one-of1-links';

/**
 * @type ProjectsUpdateByProjectIdResponseDataRelationshipsTarget
 * @export
 */
export type ProjectsUpdateByProjectIdResponseDataRelationshipsTarget = ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf | ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf1;


