/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsUpdateByProjectIdResponseDataRelationshipsOwnerLinksRelatedOneOf } from './projects-update-by-project-id-response-data-relationships-owner-links-related-one-of';

/**
 * @type ProjectsUpdateByProjectIdResponseDataRelationshipsOwnerLinksRelated
 * @export
 */
export type ProjectsUpdateByProjectIdResponseDataRelationshipsOwnerLinksRelated = ProjectsUpdateByProjectIdResponseDataRelationshipsOwnerLinksRelatedOneOf | string;


