/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContainerBuildArgs } from './container-build-args';
import { NugetBuildArgs } from './nuget-build-args';
import { YarnBuildArgs } from './yarn-build-args';

/**
 * @type ProjectAttributesBuildArgs
 * @export
 */
export type ProjectAttributesBuildArgs = ContainerBuildArgs | NugetBuildArgs | YarnBuildArgs;


