/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectSettingsDataAttributes } from './project-settings-data-attributes';

/**
 * 
 * @export
 * @interface ProjectSettingsData
 */
export interface ProjectSettingsData {
    /**
     * 
     * @type {ProjectSettingsDataAttributes}
     * @memberof ProjectSettingsData
     */
    'attributes'?: ProjectSettingsDataAttributes;
    /**
     * 
     * @type {string}
     * @memberof ProjectSettingsData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSettingsData
     */
    'type'?: string;
}

