/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsListForOrgResponseDataInnerRelationshipsImporterLinksRelated } from './projects-list-for-org-response-data-inner-relationships-importer-links-related';

/**
 * 
 * @export
 * @interface ProjectsListForOrgResponseDataInnerRelationshipsImporterLinks
 */
export interface ProjectsListForOrgResponseDataInnerRelationshipsImporterLinks {
    /**
     * 
     * @type {ProjectsListForOrgResponseDataInnerRelationshipsImporterLinksRelated}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsImporterLinks
     */
    'related'?: ProjectsListForOrgResponseDataInnerRelationshipsImporterLinksRelated;
}

