/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsUpdateByProjectIdResponseDataRelationshipsOrganizationLinksRelatedOneOf } from './projects-update-by-project-id-response-data-relationships-organization-links-related-one-of';

/**
 * @type ProjectsUpdateByProjectIdResponseDataRelationshipsOrganizationLinksRelated
 * @export
 */
export type ProjectsUpdateByProjectIdResponseDataRelationshipsOrganizationLinksRelated = ProjectsUpdateByProjectIdResponseDataRelationshipsOrganizationLinksRelatedOneOf | string;


