/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOfData } from './projects-list-for-org-response-data-inner-relationships-target-one-of-data';
import { ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOfLinks } from './projects-list-for-org-response-data-inner-relationships-target-one-of-links';

/**
 * 
 * @export
 * @interface ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf
 */
export interface ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf {
    /**
     * 
     * @type {ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOfData}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf
     */
    'data': ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOfData;
    /**
     * 
     * @type {ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOfLinks}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf
     */
    'links': ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOfLinks;
    /**
     * Free-form object that may contain non-standard information.
     * @type {{ [key: string]: any; }}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsTargetOneOf
     */
    'meta'?: { [key: string]: any; };
}

