/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf1LinksRelated } from './projects-get-by-project-id-response-data-relationships-target-one-of1-links-related';

/**
 * 
 * @export
 * @interface ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf1Links
 */
export interface ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf1Links {
    /**
     * 
     * @type {ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf1LinksRelated}
     * @memberof ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf1Links
     */
    'related'?: ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf1LinksRelated;
}

