/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfData } from './projects-update-by-project-id-response-data-relationships-target-one-of-data';
import { ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinks } from './projects-update-by-project-id-response-data-relationships-target-one-of-links';

/**
 * 
 * @export
 * @interface ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf
 */
export interface ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf {
    /**
     * 
     * @type {ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfData}
     * @memberof ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf
     */
    'data': ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfData;
    /**
     * 
     * @type {ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinks}
     * @memberof ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf
     */
    'links': ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinks;
    /**
     * Free-form object that may contain non-standard information.
     * @type {{ [key: string]: any; }}
     * @memberof ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOf
     */
    'meta'?: { [key: string]: any; };
}

