/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfData } from './projects-get-by-project-id-response-data-relationships-target-one-of-data';
import { ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfLinks } from './projects-get-by-project-id-response-data-relationships-target-one-of-links';

/**
 * 
 * @export
 * @interface ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf
 */
export interface ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf {
    /**
     * 
     * @type {ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfData}
     * @memberof ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf
     */
    'data': ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfData;
    /**
     * 
     * @type {ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfLinks}
     * @memberof ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf
     */
    'links': ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfLinks;
    /**
     * Free-form object that may contain non-standard information.
     * @type {{ [key: string]: any; }}
     * @memberof ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOf
     */
    'meta'?: { [key: string]: any; };
}

