/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfData
 */
export interface ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfData {
    /**
     * 
     * @type {string}
     * @memberof ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfData
     */
    'id': string;
    /**
     * Type of the related resource
     * @type {string}
     * @memberof ProjectsGetByProjectIdResponseDataRelationshipsTargetOneOfData
     */
    'type': string;
}

