/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinksRelated } from './projects-update-by-project-id-response-data-relationships-target-one-of-links-related';

/**
 * 
 * @export
 * @interface ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinks
 */
export interface ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinks {
    /**
     * 
     * @type {ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinksRelated}
     * @memberof ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinks
     */
    'related'?: ProjectsUpdateByProjectIdResponseDataRelationshipsTargetOneOfLinksRelated;
}

