/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProjectsListForOrgResponseDataInnerRelationshipsImporterData } from './projects-list-for-org-response-data-inner-relationships-importer-data';
import { ProjectsListForOrgResponseDataInnerRelationshipsImporterLinks } from './projects-list-for-org-response-data-inner-relationships-importer-links';

/**
 * 
 * @export
 * @interface ProjectsListForOrgResponseDataInnerRelationshipsImporter
 */
export interface ProjectsListForOrgResponseDataInnerRelationshipsImporter {
    /**
     * 
     * @type {ProjectsListForOrgResponseDataInnerRelationshipsImporterData}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsImporter
     */
    'data': ProjectsListForOrgResponseDataInnerRelationshipsImporterData;
    /**
     * 
     * @type {ProjectsListForOrgResponseDataInnerRelationshipsImporterLinks}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsImporter
     */
    'links': ProjectsListForOrgResponseDataInnerRelationshipsImporterLinks;
    /**
     * Free-form object that may contain non-standard information.
     * @type {{ [key: string]: any; }}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsImporter
     */
    'meta'?: { [key: string]: any; };
}

