/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProjectsListForOrgResponseDataInnerRelationshipsOwnerData
 */
export interface ProjectsListForOrgResponseDataInnerRelationshipsOwnerData {
    /**
     * 
     * @type {string}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsOwnerData
     */
    'id': string;
    /**
     * Type of the related resource
     * @type {string}
     * @memberof ProjectsListForOrgResponseDataInnerRelationshipsOwnerData
     */
    'type': string;
}

