/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PublicTargetAttributes
 */
export interface PublicTargetAttributes {
    /**
     * The creation date of the target
     * @type {string}
     * @memberof PublicTargetAttributes
     */
    'created_at'?: string;
    /**
     * The human readable name that represents this target. These are generated based on the provided properties, and the source. 
     * @type {string}
     * @memberof PublicTargetAttributes
     */
    'display_name': string;
    /**
     * If the target is private, or publicly accessible
     * @type {boolean}
     * @memberof PublicTargetAttributes
     */
    'is_private': boolean;
    /**
     * The URL for the resource.
     * @type {string}
     * @memberof PublicTargetAttributes
     */
    'url': string | null;
}

