/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicTargetAttributes } from './public-target-attributes';
import { PublicTargetRelationships } from './public-target-relationships';

/**
 * 
 * @export
 * @interface PublicTarget
 */
export interface PublicTarget {
    /**
     * 
     * @type {PublicTargetAttributes}
     * @memberof PublicTarget
     */
    'attributes': PublicTargetAttributes;
    /**
     * The id of this target
     * @type {string}
     * @memberof PublicTarget
     */
    'id': string;
    /**
     * 
     * @type {PublicTargetRelationships}
     * @memberof PublicTarget
     */
    'relationships'?: PublicTargetRelationships;
    /**
     * Content type.
     * @type {string}
     * @memberof PublicTarget
     */
    'type': string;
}

