/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicTargetRelationshipsOrganizationData } from './public-target-relationships-organization-data';

/**
 * The organization which owns this target
 * @export
 * @interface PublicTargetRelationshipsOrganization
 */
export interface PublicTargetRelationshipsOrganization {
    /**
     * 
     * @type {PublicTargetRelationshipsOrganizationData}
     * @memberof PublicTargetRelationshipsOrganization
     */
    'data': PublicTargetRelationshipsOrganizationData;
}

