/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PublicTargetRelationshipsIntegrationData } from './public-target-relationships-integration-data';

/**
 * The configured integration which this target relates to
 * @export
 * @interface PublicTargetRelationshipsIntegration
 */
export interface PublicTargetRelationshipsIntegration {
    /**
     * 
     * @type {PublicTargetRelationshipsIntegrationData}
     * @memberof PublicTargetRelationshipsIntegration
     */
    'data': PublicTargetRelationshipsIntegrationData;
}

