/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PublicAppDataAttributes
 */
export interface PublicAppDataAttributes {
    /**
     * 
     * @type {string}
     * @memberof PublicAppDataAttributes
     */
    'client_id': string;
    /**
     * Allow installing the app to a org/group or to a user, default tenant.
     * @type {string}
     * @memberof PublicAppDataAttributes
     */
    'context'?: PublicAppDataAttributesContextEnum;
    /**
     * New name of the app to display to users during authorization flow.
     * @type {string}
     * @memberof PublicAppDataAttributes
     */
    'name': string;
    /**
     * The scopes this app is allowed to request during authorization.
     * @type {Array<string>}
     * @memberof PublicAppDataAttributes
     */
    'scopes'?: Array<string>;
}

type PublicAppDataAttributesContextEnum = 'tenant' | 'user'


