/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RelatedLinkRelatedOneOf } from './related-link-related-one-of';

/**
 * @type RelatedLinkRelated
 * @export
 */
export type RelatedLinkRelated = RelatedLinkRelatedOneOf | string;


