/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RemedyMetadata } from './remedy-metadata';

/**
 * 
 * @export
 * @interface Remedy
 */
export interface Remedy {
    /**
     * A markdown-formatted optional description of this remedy. Links are not permitted.
     * @type {string}
     * @memberof Remedy
     */
    'description'?: string;
    /**
     * An optional identifier for correlating remedies between coordinates or across issues. They are scoped to a single Project and test run. Remedies with the same correlation_id must have the same contents. 
     * @type {string}
     * @memberof Remedy
     */
    'correlation_id'?: string;
    /**
     * 
     * @type {RemedyMetadata}
     * @memberof Remedy
     */
    'meta'?: RemedyMetadata;
    /**
     * 
     * @type {string}
     * @memberof Remedy
     */
    'type': RemedyTypeEnum;
}

type RemedyTypeEnum = 'indeterminate' | 'manual' | 'automated' | 'rule_result_message' | 'terraform' | 'cloudformation' | 'cli' | 'kubernetes' | 'arm'


