/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * An object that contains an opaque identifying string.
 * @export
 * @interface ResourcePathRepresentation
 */
export interface ResourcePathRepresentation {
    /**
     * 
     * @type {string}
     * @memberof ResourcePathRepresentation
     */
    'resource_path': string;
}

