/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RiskFactor } from './risk-factor';
import { RiskScore } from './risk-score';

/**
 * Risk prioritization information for an issue
 * @export
 * @interface Risk
 */
export interface Risk {
    /**
     * Risk factors identified for an issue
     * @type {Array<RiskFactor>}
     * @memberof Risk
     */
    'factors': Array<RiskFactor>;
    /**
     * 
     * @type {RiskScore}
     * @memberof Risk
     */
    'score'?: RiskScore;
}

