/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Risk prioritization score based on an analysis model
 * @export
 * @interface RiskScore
 */
export interface RiskScore {
    /**
     * Risk scoring model used to calculate the score value
     * @type {string}
     * @memberof RiskScore
     */
    'model': string;
    /**
     * 
     * @type {string}
     * @memberof RiskScore
     */
    'updated_at'?: string;
    /**
     * Risk score value, which may be used for overall prioritization
     * @type {number}
     * @memberof RiskScore
     */
    'value': number;
}

