/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DeployedRiskFactor } from './deployed-risk-factor';
import { OSConditionRiskFactor } from './oscondition-risk-factor';
import { PublicFacingRiskFactor } from './public-facing-risk-factor';
import { RiskFactorLinks } from './risk-factor-links';

/**
 * @type RiskFactor
 * @export
 */
export type RiskFactor = { name: 'deployed' } & DeployedRiskFactor | { name: 'os_condition' } & OSConditionRiskFactor | { name: 'public_facing' } & PublicFacingRiskFactor;


