/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SastSettingsToggleSnykCodeSettingsRequestDataAttributes
 */
export interface SastSettingsToggleSnykCodeSettingsRequestDataAttributes {
    /**
     * The value of the updated settings for sastEnabled setting
     * @type {boolean}
     * @memberof SastSettingsToggleSnykCodeSettingsRequestDataAttributes
     */
    'sast_enabled': boolean;
}

