/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SastSettingsToggleSnykCodeSettingsRequestDataAttributes } from './sast-settings-toggle-snyk-code-settings-request-data-attributes';

/**
 * 
 * @export
 * @interface SastSettingsToggleSnykCodeSettingsRequestData
 */
export interface SastSettingsToggleSnykCodeSettingsRequestData {
    /**
     * 
     * @type {SastSettingsToggleSnykCodeSettingsRequestDataAttributes}
     * @memberof SastSettingsToggleSnykCodeSettingsRequestData
     */
    'attributes': SastSettingsToggleSnykCodeSettingsRequestDataAttributes;
    /**
     * 
     * @type {string}
     * @memberof SastSettingsToggleSnykCodeSettingsRequestData
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SastSettingsToggleSnykCodeSettingsRequestData
     */
    'type': string;
}

