/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SastSettingsToggleSnykCodeSettingsRequestData } from './sast-settings-toggle-snyk-code-settings-request-data';

/**
 * 
 * @export
 * @interface SastSettingsToggleSnykCodeSettingsRequest
 */
export interface SastSettingsToggleSnykCodeSettingsRequest {
    /**
     * 
     * @type {SastSettingsToggleSnykCodeSettingsRequestData}
     * @memberof SastSettingsToggleSnykCodeSettingsRequest
     */
    'data': SastSettingsToggleSnykCodeSettingsRequestData;
}

