/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LinkProperty } from './link-property';

/**
 * 
 * @export
 * @interface SelfLink
 */
export interface SelfLink {
    /**
     * 
     * @type {LinkProperty}
     * @memberof SelfLink
     */
    'self'?: LinkProperty;
}

