/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsCreateGroupResponseDataLinksRelatedOneOf } from './service-accounts-create-group-response-data-links-related-one-of';

/**
 * @type ServiceAccountsCreateGroupResponseDataLinksRelated
 * @export
 */
export type ServiceAccountsCreateGroupResponseDataLinksRelated = ServiceAccountsCreateGroupResponseDataLinksRelatedOneOf | string;


