/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsCreateGroupResponseDataLinksSelfOneOf } from './service-accounts-create-group-response-data-links-self-one-of';

/**
 * @type ServiceAccountsCreateGroupResponseDataLinksSelf
 * @export
 */
export type ServiceAccountsCreateGroupResponseDataLinksSelf = ServiceAccountsCreateGroupResponseDataLinksSelfOneOf | string;


