/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';
import { Links } from './links';
import { ServiceAccountsManageClientSecretResponseData } from './service-accounts-manage-client-secret-response-data';

/**
 * 
 * @export
 * @interface ServiceAccountsManageClientSecretResponse
 */
export interface ServiceAccountsManageClientSecretResponse {
    /**
     * 
     * @type {ServiceAccountsManageClientSecretResponseData}
     * @memberof ServiceAccountsManageClientSecretResponse
     */
    'data': ServiceAccountsManageClientSecretResponseData;
    /**
     * 
     * @type {JsonApi}
     * @memberof ServiceAccountsManageClientSecretResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {Links}
     * @memberof ServiceAccountsManageClientSecretResponse
     */
    'links'?: Links;
}

