/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsManageClientSecretResponseDataLinksSelfOneOf } from './service-accounts-manage-client-secret-response-data-links-self-one-of';

/**
 * @type ServiceAccountsManageClientSecretResponseDataLinksSelf
 * @export
 */
export type ServiceAccountsManageClientSecretResponseDataLinksSelf = ServiceAccountsManageClientSecretResponseDataLinksSelfOneOf | string;


