/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksNextOneOf } from './service-accounts-manage-client-secret-for-organization-service-account-response-data-links-next-one-of';

/**
 * @type ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksNext
 * @export
 */
export type ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksNext = ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksNextOneOf | string;


