/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountAttributes } from './service-account-attributes';
import { ServiceAccountsUpdateGroupNameByIdResponseDataLinks } from './service-accounts-update-group-name-by-id-response-data-links';

/**
 * 
 * @export
 * @interface ServiceAccountsUpdateGroupNameByIdResponseData
 */
export interface ServiceAccountsUpdateGroupNameByIdResponseData {
    /**
     * 
     * @type {ServiceAccountAttributes}
     * @memberof ServiceAccountsUpdateGroupNameByIdResponseData
     */
    'attributes': ServiceAccountAttributes;
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountsUpdateGroupNameByIdResponseData
     */
    'id': string;
    /**
     * 
     * @type {ServiceAccountsUpdateGroupNameByIdResponseDataLinks}
     * @memberof ServiceAccountsUpdateGroupNameByIdResponseData
     */
    'links'?: ServiceAccountsUpdateGroupNameByIdResponseDataLinks;
    /**
     * 
     * @type {string}
     * @memberof ServiceAccountsUpdateGroupNameByIdResponseData
     */
    'type': string;
}

