/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksSelfOneOf } from './service-accounts-list-group-service-accounts-response-data-inner-links-self-one-of';

/**
 * @type ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksSelf
 * @export
 */
export type ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksSelf = ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksSelfOneOf | string;


