/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksPrevOneOf } from './service-accounts-list-group-service-accounts-response-data-inner-links-prev-one-of';

/**
 * @type ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksPrev
 * @export
 */
export type ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksPrev = ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksPrevOneOf | string;


