/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsUpdateGroupNameByIdResponseDataLinksSelfOneOf } from './service-accounts-update-group-name-by-id-response-data-links-self-one-of';

/**
 * @type ServiceAccountsUpdateGroupNameByIdResponseDataLinksSelf
 * @export
 */
export type ServiceAccountsUpdateGroupNameByIdResponseDataLinksSelf = ServiceAccountsUpdateGroupNameByIdResponseDataLinksSelfOneOf | string;


