/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsUpdateGroupNameByIdResponseDataLinksLastOneOf } from './service-accounts-update-group-name-by-id-response-data-links-last-one-of';

/**
 * @type ServiceAccountsUpdateGroupNameByIdResponseDataLinksLast
 * @export
 */
export type ServiceAccountsUpdateGroupNameByIdResponseDataLinksLast = ServiceAccountsUpdateGroupNameByIdResponseDataLinksLastOneOf | string;


