/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsManageClientSecretRequestData } from './service-accounts-manage-client-secret-request-data';

/**
 * 
 * @export
 * @interface ServiceAccountsManageClientSecretForOrganizationServiceAccountRequest
 */
export interface ServiceAccountsManageClientSecretForOrganizationServiceAccountRequest {
    /**
     * 
     * @type {ServiceAccountsManageClientSecretRequestData}
     * @memberof ServiceAccountsManageClientSecretForOrganizationServiceAccountRequest
     */
    'data': ServiceAccountsManageClientSecretRequestData;
}

