/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksFirst } from './service-accounts-manage-client-secret-for-organization-service-account-response-data-links-first';
import { ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksLast } from './service-accounts-manage-client-secret-for-organization-service-account-response-data-links-last';
import { ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksNext } from './service-accounts-manage-client-secret-for-organization-service-account-response-data-links-next';
import { ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksPrev } from './service-accounts-manage-client-secret-for-organization-service-account-response-data-links-prev';
import { ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksRelated } from './service-accounts-manage-client-secret-for-organization-service-account-response-data-links-related';
import { ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksSelf } from './service-accounts-manage-client-secret-for-organization-service-account-response-data-links-self';

/**
 * 
 * @export
 * @interface ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinks
 */
export interface ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinks {
    /**
     * 
     * @type {ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksFirst}
     * @memberof ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinks
     */
    'first'?: ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksFirst;
    /**
     * 
     * @type {ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksLast}
     * @memberof ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinks
     */
    'last'?: ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksLast;
    /**
     * 
     * @type {ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksNext}
     * @memberof ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinks
     */
    'next'?: ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksNext;
    /**
     * 
     * @type {ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksPrev}
     * @memberof ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinks
     */
    'prev'?: ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksPrev;
    /**
     * 
     * @type {ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksRelated}
     * @memberof ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinks
     */
    'related'?: ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksRelated;
    /**
     * 
     * @type {ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksSelf}
     * @memberof ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinks
     */
    'self'?: ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksSelf;
}

