/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksFirst } from './service-accounts-list-group-service-accounts-response-data-inner-links-first';
import { ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksLast } from './service-accounts-list-group-service-accounts-response-data-inner-links-last';
import { ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksNext } from './service-accounts-list-group-service-accounts-response-data-inner-links-next';
import { ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksPrev } from './service-accounts-list-group-service-accounts-response-data-inner-links-prev';
import { ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksRelated } from './service-accounts-list-group-service-accounts-response-data-inner-links-related';
import { ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksSelf } from './service-accounts-list-group-service-accounts-response-data-inner-links-self';

/**
 * 
 * @export
 * @interface ServiceAccountsListGroupServiceAccountsResponseDataInnerLinks
 */
export interface ServiceAccountsListGroupServiceAccountsResponseDataInnerLinks {
    /**
     * 
     * @type {ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksFirst}
     * @memberof ServiceAccountsListGroupServiceAccountsResponseDataInnerLinks
     */
    'first'?: ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksFirst;
    /**
     * 
     * @type {ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksLast}
     * @memberof ServiceAccountsListGroupServiceAccountsResponseDataInnerLinks
     */
    'last'?: ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksLast;
    /**
     * 
     * @type {ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksNext}
     * @memberof ServiceAccountsListGroupServiceAccountsResponseDataInnerLinks
     */
    'next'?: ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksNext;
    /**
     * 
     * @type {ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksPrev}
     * @memberof ServiceAccountsListGroupServiceAccountsResponseDataInnerLinks
     */
    'prev'?: ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksPrev;
    /**
     * 
     * @type {ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksRelated}
     * @memberof ServiceAccountsListGroupServiceAccountsResponseDataInnerLinks
     */
    'related'?: ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksRelated;
    /**
     * 
     * @type {ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksSelf}
     * @memberof ServiceAccountsListGroupServiceAccountsResponseDataInnerLinks
     */
    'self'?: ServiceAccountsListGroupServiceAccountsResponseDataInnerLinksSelf;
}

