/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ServiceAccountsUpdateOrganizationServiceAccountNameResponseDataLinksPrevOneOf
 */
export interface ServiceAccountsUpdateOrganizationServiceAccountNameResponseDataLinksPrevOneOf {
    /**
     * A string containing the link’s URL.
     * @type {string}
     * @memberof ServiceAccountsUpdateOrganizationServiceAccountNameResponseDataLinksPrevOneOf
     */
    'href': string;
    /**
     * Free-form object that may contain non-standard information.
     * @type {{ [key: string]: any; }}
     * @memberof ServiceAccountsUpdateOrganizationServiceAccountNameResponseDataLinksPrevOneOf
     */
    'meta'?: { [key: string]: any; };
}

