/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsUpdateOrganizationServiceAccountNameRequestData } from './service-accounts-update-organization-service-account-name-request-data';

/**
 * 
 * @export
 * @interface ServiceAccountsUpdateOrganizationServiceAccountNameRequest
 */
export interface ServiceAccountsUpdateOrganizationServiceAccountNameRequest {
    /**
     * 
     * @type {ServiceAccountsUpdateOrganizationServiceAccountNameRequestData}
     * @memberof ServiceAccountsUpdateOrganizationServiceAccountNameRequest
     */
    'data': ServiceAccountsUpdateOrganizationServiceAccountNameRequestData;
}

