/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsManageClientSecretRequestDataAttributes } from './service-accounts-manage-client-secret-request-data-attributes';

/**
 * 
 * @export
 * @interface ServiceAccountsManageClientSecretRequestData
 */
export interface ServiceAccountsManageClientSecretRequestData {
    /**
     * 
     * @type {ServiceAccountsManageClientSecretRequestDataAttributes}
     * @memberof ServiceAccountsManageClientSecretRequestData
     */
    'attributes': ServiceAccountsManageClientSecretRequestDataAttributes;
    /**
     * The Resource type.
     * @type {string}
     * @memberof ServiceAccountsManageClientSecretRequestData
     */
    'type': ServiceAccountsManageClientSecretRequestDataTypeEnum;
}

type ServiceAccountsManageClientSecretRequestDataTypeEnum = 'service_account'


