/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsCreateForOrganizationResponseDataLinksSelfOneOf } from './service-accounts-create-for-organization-response-data-links-self-one-of';

/**
 * @type ServiceAccountsCreateForOrganizationResponseDataLinksSelf
 * @export
 */
export type ServiceAccountsCreateForOrganizationResponseDataLinksSelf = ServiceAccountsCreateForOrganizationResponseDataLinksSelfOneOf | string;


