/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountLinksFirst } from './service-account-links-first';
import { ServiceAccountLinksLast } from './service-account-links-last';
import { ServiceAccountLinksNext } from './service-account-links-next';
import { ServiceAccountLinksPrev } from './service-account-links-prev';
import { ServiceAccountLinksRelated } from './service-account-links-related';
import { ServiceAccountLinksSelf } from './service-account-links-self';

/**
 * 
 * @export
 * @interface ServiceAccountLinks
 */
export interface ServiceAccountLinks {
    /**
     * 
     * @type {ServiceAccountLinksFirst}
     * @memberof ServiceAccountLinks
     */
    'first'?: ServiceAccountLinksFirst;
    /**
     * 
     * @type {ServiceAccountLinksLast}
     * @memberof ServiceAccountLinks
     */
    'last'?: ServiceAccountLinksLast;
    /**
     * 
     * @type {ServiceAccountLinksNext}
     * @memberof ServiceAccountLinks
     */
    'next'?: ServiceAccountLinksNext;
    /**
     * 
     * @type {ServiceAccountLinksPrev}
     * @memberof ServiceAccountLinks
     */
    'prev'?: ServiceAccountLinksPrev;
    /**
     * 
     * @type {ServiceAccountLinksRelated}
     * @memberof ServiceAccountLinks
     */
    'related'?: ServiceAccountLinksRelated;
    /**
     * 
     * @type {ServiceAccountLinksSelf}
     * @memberof ServiceAccountLinks
     */
    'self'?: ServiceAccountLinksSelf;
}

