/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsGetOrganizationAccountByIdResponseDataLinksFirstOneOf } from './service-accounts-get-organization-account-by-id-response-data-links-first-one-of';

/**
 * @type ServiceAccountsGetOrganizationAccountByIdResponseDataLinksFirst
 * @export
 */
export type ServiceAccountsGetOrganizationAccountByIdResponseDataLinksFirst = ServiceAccountsGetOrganizationAccountByIdResponseDataLinksFirstOneOf | string;


