/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';
import { Links } from './links';
import { ServiceAccountsUpdateGroupNameByIdResponseData } from './service-accounts-update-group-name-by-id-response-data';

/**
 * 
 * @export
 * @interface ServiceAccountsUpdateGroupNameByIdResponse
 */
export interface ServiceAccountsUpdateGroupNameByIdResponse {
    /**
     * 
     * @type {ServiceAccountsUpdateGroupNameByIdResponseData}
     * @memberof ServiceAccountsUpdateGroupNameByIdResponse
     */
    'data': ServiceAccountsUpdateGroupNameByIdResponseData;
    /**
     * 
     * @type {JsonApi}
     * @memberof ServiceAccountsUpdateGroupNameByIdResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {Links}
     * @memberof ServiceAccountsUpdateGroupNameByIdResponse
     */
    'links': Links;
}

