/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsCreateForOrganizationResponseDataLinksFirst } from './service-accounts-create-for-organization-response-data-links-first';
import { ServiceAccountsCreateForOrganizationResponseDataLinksLast } from './service-accounts-create-for-organization-response-data-links-last';
import { ServiceAccountsCreateForOrganizationResponseDataLinksNext } from './service-accounts-create-for-organization-response-data-links-next';
import { ServiceAccountsCreateForOrganizationResponseDataLinksPrev } from './service-accounts-create-for-organization-response-data-links-prev';
import { ServiceAccountsCreateForOrganizationResponseDataLinksRelated } from './service-accounts-create-for-organization-response-data-links-related';
import { ServiceAccountsCreateForOrganizationResponseDataLinksSelf } from './service-accounts-create-for-organization-response-data-links-self';

/**
 * 
 * @export
 * @interface ServiceAccountsCreateForOrganizationResponseDataLinks
 */
export interface ServiceAccountsCreateForOrganizationResponseDataLinks {
    /**
     * 
     * @type {ServiceAccountsCreateForOrganizationResponseDataLinksFirst}
     * @memberof ServiceAccountsCreateForOrganizationResponseDataLinks
     */
    'first'?: ServiceAccountsCreateForOrganizationResponseDataLinksFirst;
    /**
     * 
     * @type {ServiceAccountsCreateForOrganizationResponseDataLinksLast}
     * @memberof ServiceAccountsCreateForOrganizationResponseDataLinks
     */
    'last'?: ServiceAccountsCreateForOrganizationResponseDataLinksLast;
    /**
     * 
     * @type {ServiceAccountsCreateForOrganizationResponseDataLinksNext}
     * @memberof ServiceAccountsCreateForOrganizationResponseDataLinks
     */
    'next'?: ServiceAccountsCreateForOrganizationResponseDataLinksNext;
    /**
     * 
     * @type {ServiceAccountsCreateForOrganizationResponseDataLinksPrev}
     * @memberof ServiceAccountsCreateForOrganizationResponseDataLinks
     */
    'prev'?: ServiceAccountsCreateForOrganizationResponseDataLinksPrev;
    /**
     * 
     * @type {ServiceAccountsCreateForOrganizationResponseDataLinksRelated}
     * @memberof ServiceAccountsCreateForOrganizationResponseDataLinks
     */
    'related'?: ServiceAccountsCreateForOrganizationResponseDataLinksRelated;
    /**
     * 
     * @type {ServiceAccountsCreateForOrganizationResponseDataLinksSelf}
     * @memberof ServiceAccountsCreateForOrganizationResponseDataLinks
     */
    'self'?: ServiceAccountsCreateForOrganizationResponseDataLinksSelf;
}

