/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksRelatedOneOf } from './service-accounts-manage-client-secret-for-organization-service-account-response-data-links-related-one-of';

/**
 * @type ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksRelated
 * @export
 */
export type ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksRelated = ServiceAccountsManageClientSecretForOrganizationServiceAccountResponseDataLinksRelatedOneOf | string;


