/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceAccountsListOrganizationServiceAccountsResponseDataInnerLinksRelatedOneOf } from './service-accounts-list-organization-service-accounts-response-data-inner-links-related-one-of';

/**
 * @type ServiceAccountsListOrganizationServiceAccountsResponseDataInnerLinksRelated
 * @export
 */
export type ServiceAccountsListOrganizationServiceAccountsResponseDataInnerLinksRelated = ServiceAccountsListOrganizationServiceAccountsResponseDataInnerLinksRelatedOneOf | string;


