/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Minimum Snyk issue severity to send a notification for, messages will not be sent for any issue below this value
 * @export
 * @enum {string}
 */
export type SeverityThreshold = 'low' | 'medium' | 'high' | 'critical'

