/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';
import { ProjectSettingsData } from './project-settings-data';
import { SelfLink } from './self-link';

/**
 * 
 * @export
 * @interface SlackSettingsProjectOverrideResponse
 */
export interface SlackSettingsProjectOverrideResponse {
    /**
     * 
     * @type {ProjectSettingsData}
     * @memberof SlackSettingsProjectOverrideResponse
     */
    'data'?: ProjectSettingsData;
    /**
     * 
     * @type {JsonApi}
     * @memberof SlackSettingsProjectOverrideResponse
     */
    'jsonapi'?: JsonApi;
    /**
     * 
     * @type {SelfLink}
     * @memberof SlackSettingsProjectOverrideResponse
     */
    'links'?: SelfLink;
}

