/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';
import { SelfLink } from './self-link';
import { SlackChannel } from './slack-channel';

/**
 * 
 * @export
 * @interface SlackGetChannelNameByIdResponse
 */
export interface SlackGetChannelNameByIdResponse {
    /**
     * 
     * @type {SlackChannel}
     * @memberof SlackGetChannelNameByIdResponse
     */
    'data': SlackChannel;
    /**
     * 
     * @type {JsonApi}
     * @memberof SlackGetChannelNameByIdResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {SelfLink}
     * @memberof SlackGetChannelNameByIdResponse
     */
    'links': SelfLink;
}

