/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SlackDefaultSettingsDataAttributes } from './slack-default-settings-data-attributes';

/**
 * 
 * @export
 * @interface SlackDefaultSettingsData
 */
export interface SlackDefaultSettingsData {
    /**
     * 
     * @type {SlackDefaultSettingsDataAttributes}
     * @memberof SlackDefaultSettingsData
     */
    'attributes'?: SlackDefaultSettingsDataAttributes;
    /**
     * 
     * @type {string}
     * @memberof SlackDefaultSettingsData
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SlackDefaultSettingsData
     */
    'type'?: string;
}

