/*
Snyk API

Missing description placeholder

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JsonApi } from './json-api';
import { Links } from './links';
import { PublicTarget } from './public-target';
import { TargetsListByOrgIdResponseMeta } from './targets-list-by-org-id-response-meta';

/**
 * 
 * @export
 * @interface TargetsListByOrgIdResponse
 */
export interface TargetsListByOrgIdResponse {
    /**
     * 
     * @type {Array<PublicTarget>}
     * @memberof TargetsListByOrgIdResponse
     */
    'data': Array<PublicTarget>;
    /**
     * 
     * @type {JsonApi}
     * @memberof TargetsListByOrgIdResponse
     */
    'jsonapi': JsonApi;
    /**
     * 
     * @type {Links}
     * @memberof TargetsListByOrgIdResponse
     */
    'links': Links;
    /**
     * 
     * @type {TargetsListByOrgIdResponseMeta}
     * @memberof TargetsListByOrgIdResponse
     */
    'meta'?: TargetsListByOrgIdResponseMeta;
}

