/*
Snyk API

Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

The version of the OpenAPI document: REST


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Single Selection Versioning Schema allows manual setting of which image should be given as a recommendation.  Only one image can be set as the current recommendation. If no images are set as the current selection,  no recommendation will be given.  It is recommended to use this versioning schema if your repository\'s tags aren\'t supported by the other schemas. 
 * @export
 * @interface VersioningSchemaSingleSelectionType
 */
export interface VersioningSchemaSingleSelectionType {
    /**
     * Whether this image should be the recommendation. Only one image can be selected at a given time. Setting this as true will remove previous selection. 
     * @type {boolean}
     * @memberof VersioningSchemaSingleSelectionType
     */
    'is_selected': boolean;
    /**
     * 
     * @type {string}
     * @memberof VersioningSchemaSingleSelectionType
     */
    'type': VersioningSchemaSingleSelectionTypeTypeEnum;
}

type VersioningSchemaSingleSelectionTypeTypeEnum = 'single-selection'


